/**
 * Strings UI centralisées (point d'entrée i18n futur).
 * Aucun texte visible utilisateur ne doit être hardcodé dans les composants —
 * tout passe par cet objet. Les clés techniques (ids, routes, classNames) restent inline.
 */
export const APP_NAME = "Azigo";

export const UI = {
  app: {
    name: APP_NAME,
    description: `${APP_NAME} — Cockpit`,
  },
  nav: {
    home: "Accueil",
    dashboard: "Dashboard",
    missions: "Missions",
    estimations: "Estimations",
    properties: "Biens",
    leads: "Leads",
    visits: "Visites",
    mandates: "Mandats",
    agenda: "Agenda",
    prospection: "Prospection",
    swarms: "Swarms",
    scrapers: "Scrapers",
    tools: "Outils",
    portefeuille: "Portefeuille",
    clients: "Clients",
    crm: "CRM",
    invest: "Invest",
    profile: "Profil",
    admin: "Admin",
  },
  tools: {
    eyebrow: "MySwarms",
    title: "Outils",
    empty: "Aucun outil disponible depuis l'engine.",
    uncategorized: "Non catégorisé",
    kpis: {
      total: "Outils",
      categories: "Catégories",
    },
    cols: {
      name: "Nom",
      category: "Catégorie",
      description: "Description",
    },
  },
  scrapers: {
    eyebrow: "MySwarms",
    title: "Scrapers",
    launch: "Lancer un scrape",
    launching: "Scrape en cours…",
    launchError: "Erreur lors du lancement du scrape.",
    resultOk: (n: number) =>
      `${n} annonce${n > 1 ? "s" : ""} ingérée${n > 1 ? "s" : ""}.`,
    resultEmpty: "Aucune nouvelle annonce trouvée.",
    providerApify: "Apify LeBonCoin",
    providerMoteurImmo: "MoteurImmo",
    providerNone: "Aucune source",
    zonesTitle: "Zones surveillées",
    zonesEmpty: "Aucune zone configurée.",
    recentTitle: "Annonces récentes",
    empty: "Aucune annonce scrapée pour l'instant. Lancez un scrape pour peupler le flux.",
    kpis: {
      annonces: "Annonces",
      provider: "Source",
      zones: "Zones",
    },
    cols: {
      commune: "Commune",
      type: "Type",
      prix: "Prix",
      surface: "Surface",
      source: "Source",
      date: "Collectée",
    },
  },
  missions: {
    kicker: "L'équipe IA travaille pour toi",
    launchTitle: "Lancer une mission",
    listTitle: "Tes missions",
    total: "Total",
    empty: "Aucune mission pour le moment — lance-en une ci-dessus.",
    placeholder:
      "Dis ce que tu veux accomplir. Ex : « trouver des propriétaires prêts à vendre dans le 11e et préparer une approche »",
    launchBtn: "Lancer la mission",
    launchBusy: "Je prépare la mission…",
    launchError: "La mission n'a pas pu démarrer.",
    netError: "Problème réseau — réessaie.",
    progression: "Progression",
    canvas: "Espace de travail vivant",
    doing: "Ce qui se passe",
    found: "Ce qui est déjà trouvé",
    errorTitle: "⚠ Un point bloquant",
    decisionPill: "Besoin de ton avis",
    decisionBusy: "J'enregistre ton choix…",
    decisionError: "Ton choix n'a pas pu être pris en compte — réessaie.",
    output: "Aperçu du résultat",
    hook: "Accroche",
    detail: "Détail",
    status: {
      planning: "Préparation",
      running: "En cours",
      awaiting_decision: "Ton avis",
      done: "Terminé",
      failed: "Bloqué",
      paused: "En pause",
    } as Record<string, string>,
    phase: { done: "Terminé", now: "En cours", ask: "Besoin de ton avis", todo: "En attente" } as Record<string, string>,
  },
  admin: {
    eyebrow: "Interne",
    title: "Admin",
    sub: "Santé des providers, volumétrie, observabilité — lecture seule.",
    providersTitle: "Providers",
    configured: "Configuré",
    absent: "Absent",
    countsTitle: "Volumétrie",
    estimations: "Estimations",
    leads: "Leads",
    leadsEnriched: "Leads enrichis",
    providersConfigured: "Providers configurés",
    obsTitle: "Observabilité",
    obsBody: "Erreurs → Sentry · Coûts/latence LLM → Langfuse (consoles externes).",
    jobsTitle: "Jobs",
    jobsPlaceholder: "Jobs asynchrones — disponible une fois l'async PDF activé.",
    degraded: "Base de données indisponible.",
  },
  /** Libellés partagés des composants viz (Funnel, BarList, Donut, DataTable). */
  viz: {
    empty: "Pas encore de données",
    edit: "Modifier",
    delete: "Supprimer",
    open: "Ouvrir",
    actions: "Actions",
  },
  invest: {
    dealDetail: {
      backLink: "‹ Opportunités",
      goalSuffix: "objectif",
      raiseProgressAria: "Avancement de la levée",
      stats: {
        triTarget: "TRI cible · non gar.",
        ltv: "LTV",
        duration: "Durée",
        ticketMin: "Ticket min",
        ticketMax: "Ticket max",
        raised: "Levé",
      },
      demoReserveBtn: "Réserver ma place",
      demoReserveNote:
        "Réservation non engageante · sans versement · révocable (fiche de démonstration)",
      kycCta: "Vérifier mon identité (KYC)",
      kycBanner:
        "Les chiffres financiers détaillés (waterfall, scénarios, sensibilités, cashflow) sont masqués tant que votre identité n'est pas vérifiée. La structure reste visible. Investir comporte un risque de perte en capital ; tout rendement est une cible non garantie.",
      subscriptionFunnelTitle: "Souscription — 4 étapes",
      subscriptionFunnelFoot: (sequestre: string) =>
        `Étape 1 = réservation non engageante (aucun versement). Le versement va vers un séquestre tiers : ${sequestre}. La plateforme ne détient jamais vos fonds ; remboursement intégral si le deal n'aboutit pas.`,
      stepperSteps: [
        { label: "Montant" },
        { label: "Éligibilité" },
        { label: "Signature" },
        { label: "Versement" },
      ],
      warningsTitle: "Points d'attention :",
      kpis: {
        totalCost: "Coût total projet",
        seniorDebt: "Dette senior",
        bonds: "Obligations (vous)",
        sponsorEquity: "Equity sponsor",
      },
      charts: {
        debtEquity: "Répartition dette / equity",
        useOfFunds: "Use of funds",
        waterfall: "Waterfall de distribution (scénario central)",
        scenarios: "Scénarios (TRI cible · non garanti)",
        ltv: "LTV (dette / valeur)",
        sensPrice: "Sensibilité : prix de revente → rendement",
        sensDelay: "Sensibilité : retard travaux → rendement",
        risk: "Exposition au risque (/5)",
        margin: "Marge marchand",
        gantt: "Calendrier opérationnel",
        cashflow: "Cashflow prévisionnel (J-curve)",
      },
      gate: {
        waterfall: "Détail du waterfall après vérification d'identité (KYC).",
        scenarios: "Scénarios pessimiste/optimiste après vérification d'identité (KYC).",
        sensPrice: "Sensibilité détaillée après vérification d'identité (KYC).",
        sensDelay: "Sensibilité détaillée après vérification d'identité (KYC).",
        cashflow: "Cashflow détaillé après vérification d'identité (KYC).",
      },
      obligationsDonut: "Obligations",
      useOfFundsEmpty: "Aucun poste.",
      marginLabels: {
        costTotal: "Coût total",
        resalePrice: "Prix de revente central",
      },
      marginFoot: (marge: string, margePct: string, seuil: string) =>
        `Marge : ${marge} (${margePct}) · seuil de fragilité ${seuil}.`,
      securitiesTitle: "Sûretés & sécurités",
      tokenTitle: "Token & structure",
      dataRoomTitle: "Data room — documents",
      dataRoomEmpty:
        "Aucun document publié pour le moment. Les pièces (contrat d'émission, expertise, intercreditor, K-bis) seront mises à disposition au fil de l'instruction.",
      closingTitle: "Closing — séquence",
      fineprint: (coupon: string) =>
        `Risques (non exhaustif) : perte en capital · illiquidité (lock-up) · retard/dépassement des travaux · baisse du marché · défaut de l'opérateur · risque de taux · risque réglementaire. Le coupon central retenu est de ${coupon} (cible, non garanti). Vous êtes créancier obligataire de la SAS, pas propriétaire du bien.`,
      typeLabels: {
        marchand_de_biens: "Marchand de biens",
        promotion: "Promotion",
        locatif: "Locatif",
        value_add: "Value-add",
        mixte: "Mixte",
      } as Record<string, string>,
      suretes: [
        "Hypothèque 1er rang (banque)",
        "Nantissement des titres de la SPV",
        "GAPD du sponsor",
        "Assurance dommages-ouvrage",
      ],
      closing: [
        { title: "Déblocage du séquestre vers la SAS", sub: "À l'atteinte de l'objectif + prêt accordé", state: "todo" },
        { title: "Inscription au registre légal (DEEP)", sub: "Source de vérité légale", state: "todo" },
        { title: "Mint du token ERC-3643 sur votre coffre", sub: "Miroir on-chain, après le DEEP", state: "todo" },
        { title: "Lock-up activé jusqu'à l'exit", sub: "Titres illiquides pendant l'opération", state: "todo" },
      ] as { title: string; sub: string; state: "todo" | "active" | "done" }[],
      tokenDl: {
        nature: "Nature",
        natureVal: "Titre de créance tokenisé (obligation)",
        standard: "Standard",
        standardVal: "ERC-3643 · miroir du registre légal DEEP",
        emission: "Émission",
        emissionVal: "Au closing (pas avant)",
        settlement: "Règlement",
        settlementVal: "EUR par défaut · EURC/EURe via CASP régulé",
        framework: "Cadre",
        frameworkVal: "Security token · hors MiCA pour le token",
      },
    },
    subscribe: {
      steps: [
        { label: "Montant" },
        { label: "Réserver" },
        { label: "Signature" },
        { label: "Versement" },
      ],
      status: {
        reserved: "Réservé (non engageant)",
        signed: "Signé (eIDAS)",
        funded: "Fonds en séquestre",
        allocated: "Alloué au closing",
        minted: "Token émis",
        refunded: "Remboursé",
        cancelled: "Annulé",
        withdrawn: "Rétracté",
      } as Record<string, string>,
      flowAria: "Flux des fonds : vous vers séquestre tiers vers SPV",
      flowYou: "Vous",
      flowEscrow: "Séquestre tiers",
      flowSpvFallback: "SPV",
      kycGateMessage: "Vérifiez votre identité (KYC) pour réserver votre place.",
      kycCta: "Vérifier mon identité (KYC)",
      creditorNote:
        "Vous prêtez à une société (vous êtes créancier) ; tout rendement est une cible non garantie.",
      amountLabel: "Montant de votre souscription",
      amountHint: (min: string, max: string, currency: string) =>
        `Ticket de ${min} à ${max}. Règlement en ${currency} par défaut.`,
      amountInvalid: (min: string, max: string) =>
        `Le montant doit être compris entre ${min} et ${max}.`,
      reserveBtn: "Réserver ma place",
      reserveBusy: "Réservation…",
      reserveNote: "Réservation non engageante · sans versement · révocable",
      reservedNote:
        "Votre place est réservée sans versement. Étape suivante : signer le bulletin de souscription (signature électronique eIDAS). Vous restez créancier de la société ; rien n'est versé à cette étape.",
      signBtn: "Signer le bulletin (eIDAS)",
      signBusy: "Envoi…",
      cancelReservation: "Annuler ma réservation",
      fundNote: (sequestre: string, currency: string) =>
        `Votre versement va vers un séquestre tiers (${sequestre}) — la plateforme ne reçoit jamais les fonds. Délai de rétractation de 4 jours, sans pénalité. Remboursement intégral si le deal n'aboutit pas. Règlement en ${currency} par défaut.`,
      fundBtn: "Verser vers le séquestre tiers",
      fundBusy: "Instruction…",
      fundedBanner: "Fonds reçus en séquestre tiers.",
      coolingOffActive: "Vous pouvez encore vous rétracter pendant le délai de 4 jours.",
      coolingOffExpired: "Le délai de rétractation de 4 jours est écoulé.",
      withdrawBtn: "Me rétracter (remboursement intégral)",
      cancelSubBtn: "Annuler ma souscription",
      terminalNote: (status: string) =>
        `Souscription ${status}. Vous pouvez réserver une nouvelle place ci-dessus.`,
      mySubscriptions: "Voir mes souscriptions",
      errors: {
        dealClosed: "Ce deal n'est plus ouvert à la souscription.",
        kyc: "Votre identité n'est pas encore vérifiée (KYC).",
        suitability: "Le test d'adéquation (ECSP) doit être validé avant de réserver.",
        ticketMin: (min: string) => `Le ticket minimum est de ${min}.`,
        ticketMax: (max: string) => `Le ticket maximum est de ${max}.`,
        annualCap: (remaining: string) =>
          `Plafond annuel d'investissement atteint. Capacité restante sur 12 mois : ${remaining}.`,
        annualCapGeneric: "Plafond annuel d'investissement (12 mois) atteint.",
        coolingOff: "Le délai de rétractation de 4 jours est écoulé : l'annulation n'est plus possible.",
        esignUnavailable:
          "La signature électronique n'est pas encore disponible. Réessayez plus tard ; votre réservation est conservée.",
        escrowUnavailable:
          "Le séquestre tiers n'est pas encore disponible. Réessayez plus tard ; votre souscription est conservée.",
        serviceUnavailable: "Service indisponible pour le moment. Réessayez plus tard.",
        generic: "Une erreur est survenue.",
        reserve: "Erreur lors de la réservation.",
        sign: "Erreur lors de la demande de signature.",
        fund: "Erreur lors de l'instruction de versement.",
        cancel: "Erreur lors de l'annulation.",
      },
      notices: {
        reserved: "Place réservée — sans versement, révocable à tout moment.",
        signUrl: "Demande de signature envoyée. Ouvrez le lien pour signer le bulletin.",
        signEmail: "Demande de signature envoyée. Vous recevrez le bulletin à signer par e-mail.",
        funded:
          "Instruction de versement émise vers le séquestre tiers. Délai de rétractation de 4 jours activé.",
        cancelled: "Souscription annulée. Aucun engagement ne subsiste.",
      },
    },
    /** En-têtes partagés des composants viz Invest (tables sr-only, axes, légendes). */
    charts: {
      etage: "Étage",
      montant: "Montant",
      cumul: "Cumul",
      scenario: "Scénario",
      scenarioTriCol: "TRI annualisé (cible, non garanti)",
      sensEmpty: "Données de sensibilité indisponibles.",
      pointMort: (v: string) => `Point mort : ${v}`,
      ligneZero: "Ligne zéro = seuil de perte",
    },
    marketplace: {
      eyebrow: "Invest · Opportunités",
      title: "Opportunités",
      sub: "Des obligations de SAS, deal par deal. Vous prêtez à une société — vous n'êtes pas propriétaire du bien.",
      demoBanner:
        "Données de démonstration (aucun deal ouvert en base). Les chiffres proviennent du moteur financier sur des opérations fictives.",
      infoBanner:
        "L'argent ne bouge jamais avant que vous ayez choisi et signé un deal. Aucune pré-collecte, aucune valeur consolidée : chaque opération est indépendante (1 SPV = 1 deal).",
      kpis: {
        openDeals: "Deals ouverts",
        collected: "Collecté (réel)",
        medianTri: "TRI cible médian · non gar.",
        ticketFrom: "Ticket dès",
      },
      filtersAria: "Filtres factuels",
      sortAria: "Tri (critères factuels)",
      filters: [
        "Type : Marchand de biens",
        "Type : Locatif",
        "Durée < 24 mois",
        "LTV < 70 %",
        "Sûreté : Hypothèque",
      ],
      sorts: ["Clôture proche", "TRI cible ↓", "Durée ↑", "LTV ↑", "Récent"],
      fineprint:
        "Tout chiffre de rendement est une cible non garantie. Investir comporte un risque de perte en capital et une illiquidité (lock-up jusqu'à l'exit de chaque opération). Le tri propose des critères factuels uniquement ; aucune sélection n'est faite à votre place.",
    },
    portfolio: {
      eyebrow: "Invest · Portefeuille",
      title: "Mon portefeuille",
      sub: "Vos positions, deal par deal. Chaque opération est indépendante (1 SPV = 1 deal).",
      demoBanner:
        "Données de démonstration : vous n'avez pas encore de position. Les chiffres ci-dessous illustrent l'affichage ; ils ne reflètent aucun engagement réel.",
      kpis: {
        capitalLent: "Capital prêté (cumul)",
        activePositions: "Positions actives",
        distributions: "Distributions reçues",
      },
      antiConsolidatedBefore: "Ces montants additionnent vos prêts ; ils ne constituent ",
      antiConsolidatedAfter:
        " une valorisation de marché ni une part d'un fonds. Il n'existe aucune valeur nette consolidée, aucun rééquilibrage : chaque position se dénoue à l'exit de sa propre opération.",
      positionSummary: (capital: string, units: number, tri: string, distributions: string) =>
        `Capital prêté ${capital} · ${units} obligations · TRI cible ${tri} (non garanti) · distributions reçues ${distributions}`,
      ltvCurrent: "LTV actuelle",
      viewDetail: "Voir le détail ›",
      payoutsTitle: "Distributions reçues (paiement d'une créance · variable, non garanti)",
      payoutDefaultDeal: "Opération",
      payoutDefaultType: "Versement",
      payoutUnits: (n: number) => `${n} obligations`,
      payoutStatus: { paid: "Versé", pending: "En attente" } as Record<string, string>,
      distribTypes: {
        coupon: "Coupon",
        principal: "Remboursement",
        principal_partial: "Remboursement partiel",
        performance: "Prime de performance",
        final: "Versement de sortie",
      } as Record<string, string>,
      exitsTitle: "Exits attendus (par opération · pas de fenêtre de liquidité organisée)",
      exitSub: (months: number) =>
        `Exit attendu ~M${months} · lock-up jusqu'à l'exit de cette opération`,
      fineprint:
        "La valeur estimée d'une position n'est pas une valeur nette consolidée. Fiscalité indicative : intérêts obligataires au PFU 31,4 % (2026) ou barème, IFU annuel ; la tokenisation ne crée aucun régime fiscal distinct. Consultez votre conseiller.",
    },
    operator: {
      eyebrow: "Invest · Back-office opérateur",
      title: "Mes opérations",
      sub: "Gérez vos deals deal par deal (1 SPV = 1 opération). Les rendements affichés sont des cibles non garanties.",
      dbUnavailable: "Base de données non configurée — back-office indisponible.",
      unauthorizedBefore:
        "Accès réservé aux opérateurs et administrateurs. Vous êtes créancier/investisseur : consultez les ",
      opportunitiesLink: "opportunités",
      unauthorizedAfter: ". Investir comporte un risque de perte en capital.",
      newDealBtn: "+ Nouveau deal",
      kpis: { total: "Deals (total)", open: "Ouverts", drafts: "Brouillons", targetSum: "Objectif cumulé" },
      emptyDeals:
        "Aucun deal pour le moment. Créez votre première opération — un SPV (SAS) dédié et une tranche obligataire seront créés. La publication exige un KIIS publié.",
      table: {
        deal: "Deal",
        type: "Type",
        status: "Statut",
        raised: "Levé / Objectif",
        tri: "TRI cible · non gar.",
        action: "Action",
        viewDeal: "Voir la fiche",
        closing: "Closing",
      },
      fineprint:
        "Chaque opération est indépendante (1 SPV = 1 deal) ; aucune mutualisation. Les versements transitent par un séquestre tiers, jamais par la plateforme. Tout rendement est une cible non garantie ; risque de perte en capital pour les créanciers obligataires.",
      nouveau: {
        backLink: "‹ Mes opérations",
        eyebrow: "Invest · Back-office opérateur",
        title: "Nouveau deal",
        sub: "Créez un SPV (SAS) dédié + sa tranche obligataire. Le deal naît en brouillon ; la publication exige un KIIS publié.",
        dbUnavailable: "Base de données non configurée — création indisponible.",
        unauthorized:
          "Accès réservé aux opérateurs et administrateurs. Investir comporte un risque de perte en capital ; tout rendement est une cible non garantie.",
      },
      wizard: {
        sectionIdentity: "Identité & économie de l’opération",
        legalName: "SAS émettrice (raison sociale)",
        name: "Nom commercial du deal",
        slug: "Slug (URL)",
        slugPlaceholder: "residence-xyz-lyon6",
        city: "Ville",
        dealType: "Type d’opération",
        durationLabel: "Durée cible",
        durationSuffix: "mois",
        sectionCosts: "Postes de coût",
        acquisition: "Prix d’acquisition",
        notary: "Frais de notaire",
        works: "Budget travaux",
        other: "Frais divers / portage",
        eurSuffix: "€",
        sectionFunding: "Financement",
        seniorDebt: "Dette senior",
        seniorRate: "Taux dette senior",
        seniorRateSuffix: "%/an",
        sponsorEquity: "Equity sponsor",
        targetRaise: "Obligations (objectif de levée)",
        coupon: "Coupon cible (non garanti)",
        couponSuffix: "%/an · non gar.",
        minTicket: "Ticket minimum",
        sectionExit: "Sortie & valorisation",
        resalePrice: "Prix de revente central",
        appraised: "Valeur d’expertise (base LTV)",
        sectionSettlement: "Règlement & token (cadre anti-FIA)",
        settlementCurrency: "Devise de règlement",
        settlementEur: "EUR (séquestre)",
        settlementEurc: "EURC (stablecoin régulé)",
        settlementEure: "EURe (stablecoin régulé)",
        tokenStandard: "Standard du token",
        tokenStandardErc3643: "ERC-3643 (T-REX permissionné)",
        tokenStandardErc1400: "ERC-1400 (security token)",
        previewTitle: "Prévisualisation moteur (avant publication)",
        previewTotalCost: "Coût total projet",
        previewLtv: "LTV (dette / valeur)",
        previewMargin: "Marge marchand",
        previewTriCentral: "TRI cible · scénario central · non garanti",
        scenarioPessTitle: "Scénario PESSIMISTE (pire cas)",
        scenarioPessTri: "TRI pessimiste · non garanti",
        scenarioPessPrincipal: "Capital obligataire remboursé",
        scenarioPessLoss: "Perte en capital (pessimiste)",
        previewEmpty: "Renseignez les montants pour calculer le pire cas.",
        warningsTitle: "Points d’attention du moteur :",
        escrowAckPart1: "Je confirme que les versements transiteront par un ",
        escrowAckBold1: "séquestre tiers",
        escrowAckPart2:
          " (notaire ou EMI régulée), jamais par la plateforme. Tout rendement affiché est une ",
        escrowAckBold2: "cible non garantie",
        escrowAckPart3:
          " ; les investisseurs sont créanciers obligataires et encourent un risque de perte en capital.",
        escrowError:
          "Le séquestre tiers est obligatoire : cochez l'engagement avant de créer le deal.",
        submitFallbackError: "Échec de la création",
        submit: "Créer le deal (brouillon)",
        submitBusy: "Création…",
        submitNote:
          "Le deal naît en brouillon. La publication (mise en marché) exigera un KIIS publié.",
      },
      closing: {
        kicker: "Invest · Back-office · Closing",
        kickerDvp: "Invest · Back-office · Closing (DvP)",
        title: "Closing du deal",
        dbUnavailable: "Base de données non configurée — closing indisponible.",
        unauthorized:
          "Accès réservé aux opérateurs, à l’administration et à la conformité. Investir comporte un risque de perte en capital ; les rendements affichés sont non garantis.",
        notFound: "Deal introuvable pour ce tenant.",
        backToOperations: "← Retour aux opérations",
        headerSub:
          "Closing en livraison-contre-paiement : inscription au registre DEEP (source de vérité) d’abord, puis miroir on-chain, réconciliation, et libération du séquestre en dernier. Le porteur est créancier obligataire ; rendement non garanti, risque de perte en capital.",
        dealStatusPrefix: "Statut du deal : ",
        viewPublicSheet: "Voir la fiche publique",
        sourceOfTruthBanner:
          "DEEP = source de vérité juridique (Ord. 2017-1674). Le token ERC-3643 n’en est que le miroir : en cas de divergence, le DEEP prime ; une position on-chain supérieure au DEEP met la saga en pause (escalade conformité).",
        kpiConditions: "Conditions suspensives",
        kpiFourEyes: "Double validation (4-eyes)",
        kpiFourEyesOk: "OK",
        kpiFourEyesRequired: "Requise",
        kpiFundedSubscriptions: "Souscriptions financées",
        kpiDeepUnits: "Obligations inscrites (DEEP)",
        conditionsTitle: "Conditions suspensives",
        conditionsEmpty: "Aucune condition suspensive paramétrée pour ce deal.",
        conditionsColCode: "Code",
        conditionsColLabel: "Libellé",
        conditionsColState: "État",
        conditionMet: "remplie",
        conditionPending: "en attente",
        launchTitle: "Lancer le closing (DvP)",
        launchIntro:
          "Ordre exécuté : fonds en séquestre confirmés → inscription DEEP → mint miroir (idempotent) → réconciliation → libération du séquestre vers le SPV (en dernier). En cas d’échec avant la libération, remboursement intégral des souscriptions.",
        reconTitle: "Réconciliation DEEP ↔ chaîne",
        reconLastPass: "Dernière passe : ",
        reconPaused: "pause (chaîne > DEEP)",
        reconEmpty:
          "Aucune passe enregistrée. Sans indexer chaîne branché, la réconciliation reste « legal_only » (le registre DEEP fait foi seul).",
        deepTitle: "Registre DEEP — positions (source de vérité)",
        deepEmpty: "Aucune position inscrite. Le registre se remplit à l’étape DEEP du closing.",
        deepColHolder: "Porteur (créancier)",
        deepColUnits: "Obligations",
        launcher: {
          accepted: "Closing accepté — traitement asynchrone en cours (saga DvP).",
          sagaDone: (outcome: string, compensated: boolean) =>
            `Saga terminée — issue : ${outcome}${compensated ? " (remboursement appliqué)" : ""}.`,
          fourEyesRequired: "Double validation (operator + compliance) requise avant le closing.",
          conditionsUnmet: (detail: string) =>
            `Conditions suspensives non remplies : ${detail}.`,
          conditionsUnmetFallback: "—",
          failed: "Échec du closing.",
          networkError: "Erreur réseau.",
          launch: "Lancer le closing",
          launchBusy: "Closing en cours…",
          notReady: "La double validation 4-eyes et toutes les conditions suspensives doivent être réunies.",
        },
      },
    },
    onboarding: {
      steps: [
        { label: "Profil" },
        { label: "Test ECSP" },
        { label: "Identité (KYC)" },
        { label: "Wallet" },
      ],
      aria: {
        profile: "Profil investisseur",
        assessment: "Test de connaissances ECSP",
        kyc: "Vérification d'identité",
        wallet: "Adresse wallet",
      },
      profile: {
        title: "Votre profil",
        introBefore: "En investissant ici, vous devenez ",
        introBold: "créancier",
        introAfter:
          " d'une société : vous lui prêtez, vous n'êtes pas propriétaire du bien. Ce parcours débloque votre capacité à souscrire, il ne place aucun argent.",
        fullName: "Nom complet",
        fullNamePlaceholder: "Prénom Nom",
        country: "Pays de résidence",
        countryPlaceholder: "FR",
        investorKind: "Type d'investisseur",
        naturalPerson: "Personne physique",
        legalEntity: "Personne morale",
        inviteCode: "Code d'invitation (optionnel)",
        invitePlaceholder: "Sur invitation — laissez vide au pilote",
        continue: "Continuer",
        saving: "Enregistrement…",
      },
      assessment: {
        title: "Test de connaissances et capacité de perte",
        intro:
          "Réglementation ECSP (UE 2020/1503). Trois questions, puis votre capacité de perte. Le résultat fixe votre plafond d'investissement annuel.",
        lossCapacity: "Capacité de perte (en euros)",
        annualIncome: "Revenu annuel net",
        liquidAssets: "Actifs liquides",
        commitments: "Engagements financiers annuels",
        amountPlaceholder: "0",
        back: "Retour",
        validate: "Valider le test",
        calculating: "Calcul…",
        bannerPending: "Répondez aux trois questions, puis renseignez votre capacité de perte.",
        bannerPass: (score: number, total: number) =>
          `Connaissances : ${score}/${total}. Vous serez classé non-averti ; votre plafond sera le plus élevé entre 1000 € et 5 % de votre patrimoine net.`,
        bannerFail: (score: number, total: number) =>
          `Connaissances : ${score}/${total}. Reprenez les réponses : tout rendement est non garanti et le capital comporte un risque de perte.`,
      },
      questions: [
        {
          id: "q1",
          prompt:
            "Quelle est la nature de votre titre ? Vous prêtez à une société (créance), ou vous détenez un droit réel sur l'immeuble ?",
          answer: false,
          yes: "Je détiens un droit réel sur l'immeuble",
          no: "Je suis créancier de la société (je lui prête)",
        },
        {
          id: "q2",
          prompt: "Le rendement cible affiché est-il un objectif assuré ?",
          answer: false,
          yes: "Oui, le rendement est assuré",
          no: "Non, le rendement n'est pas garanti",
        },
        {
          id: "q3",
          prompt: "Votre placement peut-il perdre de la valeur, voire la totalité du capital ?",
          answer: true,
          yes: "Oui, il existe un risque de perte en capital",
          no: "Non, le capital est protégé",
        },
      ],
      kyc: {
        title: "Vérification d'identité (KYC)",
        capLabel: "Plafond d'investissement annuel",
        capUnlimited: "Non plafonné",
        classification: (kind: string) => `Classification : ${kind}`,
        retail: "non-averti",
        sophisticated: "averti",
        intro:
          "La vérification d'identité (LCB-FT) est obligatoire avant toute souscription. Elle est opérée par un prestataire tiers ; aucune pièce n'est stockée chez nous.",
        unavailable:
          "La vérification d'identité sera bientôt disponible. Vous pouvez poursuivre votre parcours et ajouter votre wallet ; la souscription restera bloquée tant que le KYC n'est pas finalisé.",
        started: "Dossier KYC ouvert. Suivez les étapes du prestataire pour finaliser la vérification.",
        sessionToken: "Jeton de session généré.",
        statusCurrent: (status: string) => `Statut KYC actuel : ${status}.`,
        statusNotStarted: "non démarré",
        start: "Démarrer la vérification",
        starting: "Ouverture…",
        continueWallet: "Continuer vers le wallet",
      },
      wallet: {
        title: "Votre wallet",
        introBefore:
          "Vos titres seront reflétés on-chain (miroir du registre légal) sur votre wallet. Une identité ",
        introBold: "ONCHAINID",
        introAfter:
          " (non transférable) y sera rattachée à l'approbation de votre KYC : elle atteste que vous êtes vérifié, sans exposer vos données. Saisissez l'adresse manuellement.",
        addressLabel: "Adresse EVM (0x…)",
        addressPlaceholder: "0x0000000000000000000000000000000000000000",
        formatHint: "Format attendu : 0x suivi de 40 caractères hexadécimaux.",
        savedPrefix: "Wallet enregistré : ",
        onchainLinked: " · ONCHAINID rattaché.",
        onchainAfterKyc: " · ONCHAINID rattaché après approbation KYC.",
        update: "Mettre à jour",
        save: "Enregistrer le wallet",
        saving: "Enregistrement…",
      },
      doneBefore:
        "Votre profil est prêt. Vous pourrez souscrire deal par deal une fois votre KYC approuvé. Les fonds transiteront toujours par un ",
      doneBold: "séquestre",
      doneAfter: " tiers, jamais par la plateforme.",
      foot:
        "Investir comporte un risque de perte en capital et une illiquidité. Tout rendement cible est non garanti. Vous prêtez à une société (vous êtes créancier), vous n'achetez pas le bien.",
      errors: {
        profile: "Erreur lors de l'enregistrement du profil.",
        assessment: "Erreur lors du test ECSP.",
        kyc: "Erreur lors du lancement du KYC.",
        wallet: "Erreur lors de l'ajout du wallet.",
      },
    },
  },
  dashboard: {
    eyebrow: "Cockpit",
    title: "Aujourd'hui",
    newCta: "Nouveau bien",
    sub: "Ce qui mérite ton attention maintenant.",
    kpis: {
      estimations: "Estimations",
      ready: "Prêtes",
      inProgress: "En cours",
      portfolio: "Valeur portefeuille",
      properties: "Biens",
      activeLeads: "Leads actifs",
      upcomingVisits: "Visites à venir",
      activeMandates: "Mandats actifs",
    },
    today: {
      title: "À faire maintenant",
      leadsLabel: "Leads à relancer",
      visitsLabel: "Visites dans 48h",
      mandatesLabel: "Mandats expirant bientôt",
      estimationsLabel: "Estimations en cours",
      emptyLeads: "Aucun lead à relancer.",
      emptyVisits: "Aucune visite prévue.",
      emptyMandates: "Aucun mandat n'expire bientôt.",
      emptyEstimations: "Aucune estimation en cours.",
      seeAll: "Voir tous →",
    },
    actions: {
      title: "Actions principales",
      newEstimation: "Nouvelle estimation",
      newEstimationDesc: "Démarrer un entretien vendeur et générer un avis de valeur.",
      newProperty: "Nouveau bien",
      newClient: "Nouveau client",
      newVisit: "Nouvelle visite",
      launchPros: "Lancer une prospection",
      create: "Créer",
    },
    // Legacy keys kept for backwards compat
    priorities: {
      title: "Actions CRM",
      body: "Les mêmes volumes restent visibles dans le header ; ici, on garde seulement les chemins d'action.",
      leadsEyebrow: "Pipeline",
      leadsTitle: "Leads",
      leadsBody: "Qualifier, relancer et faire avancer les contacts ouverts.",
      visitsEyebrow: "Agenda",
      visitsTitle: "Visites",
      visitsBody: "Préparer les rendez-vous et vérifier les biens liés.",
      mandatesEyebrow: "Mandats",
      mandatesTitle: "Mandats",
      mandatesBody: "Suivre les mandats signés, échéances et statuts.",
      openPipeline: "Traiter",
      prepareVisits: "Préparer",
      reviewMandates: "Piloter",
    },
    commands: {
      title: "Actions rapides",
      visualAria: "Raccourcis d'action du cockpit",
      visualEyebrow: "Console",
      visualTitle: "Scraper · screener · relever · rechercher",
      visualBody: "Accès direct aux moteurs.",
      scrapeEyebrow: "Scraper",
      scrapeTitle: "Annonces",
      scrapeBody: "Ouvrir le flux des annonces ingérées et rafraîchir la lecture marché.",
      screenEyebrow: "Screener",
      screenTitle: "Matching",
      screenBody: "Voir les scores acquéreur ↔ annonce et prioriser les contacts.",
      releveEyebrow: "Relever",
      releveTitle: "Critères",
      releveBody: "Créer ou mettre à jour les profils acquéreurs à surveiller.",
      searchEyebrow: "Rechercher",
      searchTitle: "Mission",
      searchBody: "Préremplir une mission de recherche rapide depuis le cockpit.",
      searchObjective: "Recherche rapidement les meilleures opportunités immobilières à traiter aujourd'hui et propose les 3 actions prioritaires.",
      open: "Ouvrir",
      launch: "Préparer",
    },
    quick: {
      title: "Raccourcis métier",
      propertiesEyebrow: "Portefeuille",
      propertiesTitle: "Biens",
      propertiesBody: "Ouvrir le portefeuille et les fiches détaillées.",
      estimateEyebrow: "Valeur",
      estimateTitle: "Nouvelle estimation",
      estimateBody: "Démarrer un avis de valeur guidé par l'IA.",
      prospectionEyebrow: "Acquisition",
      prospectionTitle: "Prospection",
      prospectionBody: "Voir les annonces, critères acquéreurs et matchs.",
      missionsEyebrow: "IA",
      missionsTitle: "Mission",
      missionsBody: "Lancer une mission agentique en langage naturel.",
      open: "Ouvrir",
      launch: "Lancer",
    },
    portfolioPanel: {
      title: "Accès rapide",
      actions: {
        properties: "Biens",
        leads: "Leads",
        visits: "Visites",
        mandates: "Mandats",
      },
      open: "Ouvrir",
    },
    propertiesEmpty: "Aucun bien pour le moment.",
    addProperty: "Ajouter un bien",
    seeAllProperties: "Voir tous les biens",
    recentPortfolio: "Portefeuille récent",
    charts: {
      pipeline: "Pipeline estimations",
      byCity: "Répartition par ville",
      byValueBand: "Valeur estimée par tranche",
      completion: "Taux de complétion",
      completionSub: "Prêtes",
      heatmap: "Estimations par ville et statut",
    },
    heatmapNoCity: "Sans ville",
    table: {
      property: "Bien",
      status: "Statut",
      value: "Valeur",
      updated: "Maj",
      action: "",
    },
    recent: "Estimations récentes",
    seeAll: "Voir toutes les estimations",
    activity: "Activité récente",
    activityEmpty: "Aucune visite planifiée.",
    visitBadge: "Visite",
    propertyLinked: "Bien lié",
    propertyMissing: "Bien non renseigné",
    heroMeta: (n: number) =>
      `${n} estimation${n > 1 ? "s" : ""} suivie${n > 1 ? "s" : ""}`,
    donutMeta: (ready: number, total: number) =>
      `${ready} prête${ready > 1 ? "s" : ""} sur ${total}`,
    kpiHints: {
      properties: "Au portefeuille",
      activeLeads: "En cours",
      upcomingVisits: "Planifiées",
      activeMandates: "Signés actifs",
    },
    cards: {
      assistantTitle: "Assistant Kimi",
      assistantBody:
        "Le rail droit exécute Kimi K2.6 (streaming, persisté par utilisateur et tenant). Tape « mémorise : … » pour enregistrer un fait partagé du tenant, réinjecté au prochain message.",
    },
  },
  estimations: {
    eyebrow: "Cockpit",
    title: "Estimations",
    sub: "Vos avis de valeur — entretien guidé, analyse marché, brochure.",
    newCta: "Nouvelle estimation",
    empty: "Aucune estimation pour le moment. Démarrez votre premier avis de valeur.",
    kpis: {
      total: "Estimations",
      ready: "Prêtes",
      inProgress: "En cours",
      avgValue: "Valeur moy. (prêtes)",
    },
    charts: {
      pipeline: "Pipeline",
      byType: "Par type de bien",
    },
    table: {
      location: "Bien",
      type: "Type",
      value: "Valeur",
      status: "Statut",
      updated: "Maj",
      action: "",
    },
    back: "Retour aux estimations",
    interviewTitle: "Entretien",
    interviewSub: "Décrivez votre bien en quelques mots — l'assistant ne demande que l'essentiel, dans l'ordre.",
    soon: "Bientôt — le moteur d'entretien arrive.",
    generate: "Générer l'estimation",
    generating: "Calcul de l'estimation…",
    creating: "Création…",
    createError: "Erreur lors de la création.",
    downloadPdf: "Télécharger le PDF",
    share: "Partager",
    valuationTitle: "Estimation",
    low: "Fourchette basse",
    market: "Valeur de marché",
    high: "Fourchette haute",
    perSqm: "Prix au m²",
    perSqmUnit: " / m²",
    surfaceUnit: " m²",
    recommended: "Prix de mise en vente conseillé",
    adjustmentsTitle: "Ajustements",
    marketContextTitle: "Contexte marché",
    marketContextCta: "Charger le contexte marché",
    marketContextLoading: "Recherche en cours…",
    marketContextEmpty: "Contexte marché indisponible pour le moment.",
    marketContextSources: "Sources",
    marketContextHint: "Informations de contexte — n'entrent pas dans le calcul du prix.",
    adjustSeparator: " — ",
    premiumSign: "+",
    discountSign: "−",
    strategiesTitle: "Stratégies de vente",
    shareCopied: "Lien copié",
    fallbackName: "Estimation",
    resume: "Reprendre",
    open: "Ouvrir",
    ficheTitle: "Fiche bien",
    ficheEmpty: "Les champs se remplissent au fil de l'entretien.",
    toConfirm: "à confirmer",
    blockProgress: (n: number, total: number) => `Bloc ${n} / ${total}`,
    keyInfoProgress: (n: number, total: number) => `${n} / ${total} infos clés`,
    nextInfo: (label: string) => `Prochaine info : ${label}`,
    allKeyInfo: "Infos clés réunies",
    readyToGenerate: "Prêt à générer l'estimation",
    listingComparablesTitle: "Annonces en cours",
    listingComparablesLink: "Voir l'annonce",
    listingComparablesEmpty: "Aucune annonce comparable trouvée pour ce bien.",
    listingColAnnonce: "Annonce",
    listingColSource: "Source",
    listingColPrix: "Prix",
    listingColSurface: "Surface",
    listingColPrixM2: "Prix / m²",
    listingColActions: "",
    listingSourceLabels: {
      leboncoin: "LeBonCoin",
      bienici: "Bienici",
    } as Record<string, string>,
    listingFetchSourceLabels: {
      apify: "Apify (LeBonCoin)",
      myswarms: "MySwarms (Bienici) — fallback",
      none: "Aucune source configurée",
    } as Record<string, string>,
    listingFetchSourcePrefix: "Source annonces :",
    confidenceLabels: {
      indicative: "Indicative",
      moyenne: "Moyenne",
      elevee: "Élevée",
    } as Record<string, string>,
    confidenceTooltips: {
      indicative: "Estimation basée sur peu de données de marché — fourchette large.",
      moyenne: "Estimation avec données DVF partielles — bonne fiabilité.",
      elevee: "Estimation robuste, nombreux comparables DVF récents.",
    } as Record<string, string>,
    comparablesDvf: (n: number) => `${n} comparable${n > 1 ? "s" : ""} DVF`,
    recoPriceLabel: "Conseillé",
    generatingTitle: "Analyse en cours…",
    generatingSub: "Nous interrogeons les bases DVF, DPE et les annonces du marché.",
    generatingSteps: [
      "Géocodage",
      "Cadastre",
      "Sections cadastrales",
      "Mutations DVF",
      "DPE",
      "Comparables",
      "Valorisation",
      "Annonces comparables",
      "Finalisation",
    ],
    status: {
      draft: "Brouillon",
      interviewing: "Entretien en cours",
      recap: "Récapitulatif",
      valuating: "Calcul",
      ready: "Prête",
      archived: "Archivée",
    } as Record<string, string>,
    // Libellés courts (colonnes de la heatmap dashboard).
    statusShort: {
      draft: "Brn",
      interviewing: "Entr.",
      recap: "Récap",
      valuating: "Calc.",
      ready: "Prête",
      archived: "Arch.",
    } as Record<string, string>,
  },
  properties: {
    eyebrow: "Portefeuille",
    title: "Biens",
    sub: "Votre portefeuille de biens — du prospect à la vente.",
    newCta: "Nouveau bien",
    empty: "Aucun bien. Ajoutez votre premier mandat ou prospect.",
    open: "Ouvrir",
    delete: "Supprimer",
    fallbackTitle: "Bien sans titre",
    statusAria: "Statut du bien",
    statusUpdateError: "Le statut n'a pas pu être mis à jour. Réessayez.",
    cardCaracteristiques: "Caractéristiques",
    seeEstimation: "Voir l'estimation",
    fields: {
      type: "Type",
      surface: "Surface",
      rooms: "Pièces",
      bedrooms: "Chambres",
      address: "Adresse",
      postalCode: "Code postal",
      estimation: "Estimation liée",
    },
    kpis: {
      total: "Biens",
      forSale: "En vente",
      sold: "Vendus",
      portfolio: "Valeur portefeuille",
    },
    charts: {
      pipeline: "Pipeline",
      soldRate: "Taux de vente",
      soldRateSub: "Vendus",
      byType: "Par type de bien",
      byValueBand: "Prix affiché par tranche",
    },
    table: {
      title: "Bien",
      type: "Type",
      city: "Ville",
      surface: "Surface",
      price: "Prix",
      status: "Statut",
      action: "",
    },
    statusLabels: {
      prospect: "Prospect",
      estimation: "En estimation",
      mandat: "Mandat",
      en_vente: "En vente",
      sous_offre: "Sous offre",
      vendu: "Vendu",
      archive: "Archivé",
    } as Record<string, string>,
    typeLabels: {
      appartement: "Appartement",
      maison: "Maison",
      terrain: "Terrain",
      local: "Local",
      autre: "Autre",
    } as Record<string, string>,
    form: {
      title: "Bien",
      sectionMain: "Informations principales",
      sectionLocation: "Localisation",
      sectionFeatures: "Caractéristiques",
      sectionPrice: "Prix / mandat",
      name: "Titre",
      type: "Type",
      address: "Adresse",
      city: "Ville",
      postalCode: "Code postal",
      surface: "Surface (m²)",
      rooms: "Pièces",
      bedrooms: "Chambres",
      askingPrice: "Prix affiché (€)",
      notes: "Notes",
      save: "Enregistrer",
      cancel: "Annuler",
      dpeLabel: "DPE (A à G)",
      gesLabel: "GES (A à G)",
      yearBuilt: "Année de construction",
      floor: "Étage",
      floorTotal: "Nb étages total",
      orientation: "Orientation",
      chargesMonthly: "Charges mensuelles (€/mois)",
      taxeFonciere: "Taxe foncière (€/an)",
      hasParking: "Parking",
      hasElevator: "Ascenseur",
      hasGarden: "Jardin",
      hasTerrace: "Terrasse",
      hasPool: "Piscine",
      hasCellar: "Cave",
      parkingCount: "Nombre de places de parking",
    },
    dpe: {
      title: "Performance énergétique",
      label: "DPE",
      gesLabel: "GES",
      letters: { A: "A", B: "B", C: "C", D: "D", E: "E", F: "F", G: "G" } as Record<string, string>,
      none: "Non renseigné",
    },
    enrichissement: {
      title: "Informations complémentaires",
      yearBuilt: "Année de construction",
      floor: "Étage",
      floorTotal: "Nb étages",
      orientation: "Orientation",
      charges: "Charges mensuelles",
      taxeFonciere: "Taxe foncière",
      parking: "Parking",
      elevator: "Ascenseur",
      garden: "Jardin",
      terrace: "Terrasse",
      pool: "Piscine",
      cellar: "Cave",
      parkingCount: "Nb places parking",
      yes: "Oui",
      no: "Non",
    },
    photos: {
      title: "Photos",
      altFallback: "Bien immobilier",
      upload: "Ajouter des photos",
      uploading: "Upload en cours…",
      empty: "Aucune photo. Glissez-déposez ou cliquez pour en ajouter.",
      delete: "Supprimer",
      cover: "Couverture",
      error: "Erreur lors de l'upload.",
      invalidType: "Format non supporté (JPEG, PNG, WebP uniquement).",
      tooLarge: "Fichier trop volumineux (max 10 Mo).",
    },
    editBtn: "Modifier le bien",
    newVisitBtn: "Nouvelle visite",
    newMandateBtn: "Nouveau mandat",
    daysOnMarket: (d: number) => `${d} jour${d > 1 ? "s" : ""} au portefeuille`,
    // ── Vue cockpit portefeuille (par défaut)
    cockpit: {
      panelTitle: "Votre portefeuille",
      tabCockpit: "Cockpit",
      tabKanban: "Kanban",
      tabList: "Liste",
      active: "En vente / actifs",
      toComplete: "À compléter",
      recent: "Récemment ajoutés",
      closed: "Vendus / archivés",
      recentActivity: "Activité récente",
      zoneEmpty: "Rien pour l'instant",
      seeMandates: "Voir les mandats",
      seeEstimations: "Voir les estimations",
      healthTitle: "Signaux portefeuille",
      healthNoPrix: "sans prix",
      healthNoCity: "sans ville",
      healthNoType: "sans type",
      live: "● Session live",
      liveUpdated: "● Mis à jour",
      liveRefreshing: "↻ Actualisation…",
      liveHint: "Synchronisation entre les onglets de ce navigateur (intra-session).",
    },
    // Fiche détail premium
    detail: {
      cardPhotos: "Photos",
      cardCaracteristiques: "Caractéristiques",
      cardEquipements: "Équipements & prestations",
      cardLocalisation: "Localisation",
      cardDpe: "Performance énergétique",
      cardNotes: "Notes internes",
      cardLeads: "Leads intéressés",
      cardVisites: "Visites planifiées",
      cardMandats: "Mandats",
      heroPriceSuffix: "",
      pricePerSqm: (v: string) => `${v} / m²`,
      priceType: { asking: "Prix affiché", estimated: "Valeur estimée" } as Record<string, string>,
      chipSurface: (v: number) => `${v} m²`,
      chipRooms: (n: number) => `${n} pièce${n > 1 ? "s" : ""}`,
      chipBedrooms: (n: number) => `${n} chambre${n > 1 ? "s" : ""}`,
      chipFloor: (f: number, t: number | null | undefined) =>
        t != null ? `Étage ${f}/${t}` : `Étage ${f}`,
      gridYearBuilt: "Construit en",
      gridOrientation: "Orientation",
      gridCharges: "Charges",
      gridChargesSuffix: "/ mois",
      gridTaxe: "Taxe foncière",
      gridTaxeSuffix: "/ an",
      gridParking: "Parking",
      gridParkingPlaces: (n: number) => `${n} place${n > 1 ? "s" : ""}`,
      gridEstimation: "Estimation liée",
      gridUpdated: "Dernière modif.",
      equipElevator: "Ascenseur",
      equipParking: "Parking",
      equipGarden: "Jardin",
      equipTerrace: "Terrasse",
      equipPool: "Piscine",
      equipCellar: "Cave",
      locMapsLink: "Voir sur Google Maps",
      dpeNote: (l: string) => `Classe ${l}`,
      gesNote: (l: string) => `Classe ${l}`,
      notesEmpty: "Aucune note.",
      leadsEmpty: "Aucun lead associé.",
      visitsEmpty: "Aucune visite planifiée.",
      mandatesEmpty: "Aucun mandat.",
      seeAllLeads: "Voir tous les leads →",
      visitDuration: (m: number) => `${m} min`,
      mandateRef: "Sans référence",
      commission: (p: number) => `${p}%`,
    },
  },
  leads: {
    eyebrow: "Commercial",
    title: "Leads",
    sub: "Votre pipeline commercial — acheteurs et vendeurs.",
    newCta: "Nouveau lead",
    empty: "Aucun lead. Ajoutez votre premier contact.",
    delete: "Supprimer",
    // ── Vue cockpit relationnel (par défaut)
    cockpit: {
      panelTitle: "Vos clients",
      tabCockpit: "Cockpit",
      tabKanban: "Kanban",
      tabList: "Liste",
      toFollow: "À relancer",
      fresh: "Nouveaux leads",
      hotSellers: "Vendeurs chauds",
      activeBuyers: "Acquéreurs actifs",
      recentActivity: "Activité récente",
      zoneEmpty: "Rien pour l'instant",
    },
    statusUpdateError: "Le statut n'a pas pu être mis à jour. Réessayez.",
    fallbackInitials: "—",
    enrich: "Enrichir",
    enriching: "Enrichissement…",
    enrichDone: "Lead enrichi.",
    enrichNoData: "Aucune donnée exploitable trouvée.",
    enrichConsent:
      "Confirmer l'enrichissement B2B via un data broker externe ? À utiliser uniquement pour un contact professionnel avec base légale.",
    enrichErrors: {
      consent_required: "Consentement RGPD requis.",
      forbidden_particulier: "Enrichissement interdit pour un particulier.",
      invalid_body: "Demande d'enrichissement invalide.",
      no_email_to_enrich: "Un email est requis pour enrichir ce lead.",
      enrichment_not_configured: "Aucun provider d'enrichissement n'est configuré.",
      rate_limited: "Trop d'enrichissements. Réessayez dans un instant.",
      not_found: "Lead introuvable.",
    } as Record<string, string>,
    cardTitle: "Leads intéressés",
    seeAll: "Voir tous les leads",
    kpis: {
      total: "Leads",
      active: "Actifs",
      won: "Gagnés",
      conversion: "Conversion",
    },
    charts: {
      pipeline: "Pipeline commercial",
      conversionSub: "Conversion",
      conversionRate: "Taux de conversion",
    },
    table: {
      name: "Nom",
      kind: "Type",
      status: "Statut",
      budget: "Budget",
      source: "Source",
      action: "",
    },
    statusLabels: {
      nouveau: "Nouveau",
      contacte: "Contacté",
      qualifie: "Qualifié",
      visite: "En visite",
      offre: "Offre",
      gagne: "Gagné",
      perdu: "Perdu",
    } as Record<string, string>,
    kindLabels: {
      acheteur: "Acheteur",
      vendeur: "Vendeur",
    } as Record<string, string>,
    typePersonneLabels: {
      particulier: "Particulier",
      professionnel: "Professionnel",
      societe: "Société",
      sci: "SCI",
      agence: "Agence",
    } as Record<string, string>,
    form: {
      title: "Lead",
      fullName: "Nom complet",
      email: "Email",
      phone: "Téléphone",
      source: "Source",
      kind: "Type",
      typePersonne: "Nature juridique",
      budgetMin: "Budget min (€)",
      budgetMax: "Budget max (€)",
      save: "Enregistrer",
      cancel: "Annuler",
    },
    detail: {
      backLink: "‹ Leads",
      eyebrowAcheteur: "Acquéreur",
      eyebrowVendeur: "Vendeur",
      eyebrowFallback: "Lead",
      fallbackName: "Lead sans nom",
      cardIdentite: "Identité & contact",
      cardBudget: "Budget",
      cardCriteres: "Critères de recherche",
      cardVisites: "Visites liées",
      cardBienLie: "Bien lié",
      cardEnrichissement: "Enrichissement",
      fields: {
        email: "Email",
        phone: "Téléphone",
        source: "Source",
        typePersonne: "Nature juridique",
        consentAt: "Consentement RGPD",
        enrichedAt: "Enrichi le",
        enrichedSource: "Source enrichissement",
        createdAt: "Créé le",
        updatedAt: "Dernière modif.",
        status: "Statut",
        notes: "Notes",
        title: "Titre",
      },
      budgetMin: "Budget min",
      budgetMax: "Budget max",
      criteres: {
        nom: "Nom du critère",
        typeBien: "Type de bien",
        surface: "Surface",
        pieces: "Pièces",
        budget: "Budget",
        zones: "Zones",
        dpeMax: "DPE max",
        terrasse: "Terrasse",
        parking: "Parking",
        ascenseur: "Ascenseur",
        jardin: "Jardin",
        piscine: "Piscine",
        actif: "Actif",
        oui: "Oui",
        non: "Non",
        surfaceRange: (min: number, max: number) => `${min} – ${max} m²`,
        piecesRange: (min: number, max: number) => `${min} – ${max} p.`,
      },
      emptyBudget: "Budget non renseigné.",
      emptyCriteres: "Aucun critère de recherche défini.",
      emptyVisites: "Aucune visite planifiée pour ce lead.",
      emptyBienLie: "Aucun bien lié.",
      emptyEnrichissement: "Aucune donnée d'enrichissement disponible.",
      enrich: {
        cardTitle: "Enrichissement B2B",
        intro: "Récupère les données professionnelles publiques de ce contact (entreprise, poste) via nos fournisseurs partenaires. Consentement requis.",
        button: "Enrichir ce contact",
        reenrich: "Réactualiser l'enrichissement",
        busy: "Enrichissement…",
        errorGeneric: "Enrichissement indisponible pour le moment.",
        errorNoEmail: "Un email est nécessaire pour enrichir ce contact.",
        errorNotConfigured: "Enrichissement non configuré (clés fournisseur absentes).",
        empty: "Aucune donnée d'enrichissement pour l'instant.",
      },
      bienLie: {
        city: "Ville",
        price: "Prix affiché",
        type: "Type",
        seeProperty: "Voir la fiche bien ›",
      },
    },
  },
  visits: {
    eyebrow: "Visites",
    title: "Visites",
    sub: "Vos visites planifiées et passées.",
    newCta: "Planifier une visite",
    empty: "Aucune visite planifiée.",
    upcoming: "À venir",
    past: "Passées",
    delete: "Supprimer",
    cardTitle: "Visites",
    durationUnit: " min",
    kpis: {
      total: "Visites",
      upcoming: "À venir",
      done: "Réalisées",
      noShow: "No-show",
    },
    charts: {
      pipeline: "Pipeline",
      doneRate: "Taux de réalisation",
      doneRateSub: "Réalisées",
    },
    table: {
      property: "Bien",
      datetime: "Date",
      duration: "Durée",
      status: "Statut",
      action: "",
    },
    statusLabels: {
      planifiee: "Planifiée",
      confirmee: "Confirmée",
      realisee: "Réalisée",
      annulee: "Annulée",
      no_show: "No-show",
    } as Record<string, string>,
    form: {
      title: "Visite",
      property: "Bien",
      lead: "Lead",
      scheduledAt: "Date et heure",
      duration: "Durée (min)",
      notes: "Notes",
      save: "Enregistrer",
      cancel: "Annuler",
    },
  },
  prospection: {
    // ── Navigation & header
    title: "Prospection",
    kicker: "BienCible import",
    eyebrow: "Prospection",
    tabAcquereurs: "Acquéreurs",
    acquereurs: "Acquéreurs",
    annonces: "Annonces",
    matching: "Matching",
    criteres: "Critères",
    newAcquereurBtn: "+ Nouvel acquéreur",
    // ── KPI labels
    kpiAcquereurs: "Acquéreurs",
    kpiMatchs: "Matchs",
    kpiAnnonces: "Annonces",
    kpiAlertes: "Alertes",
    // ── Toolbar annonces
    eligibleOnly: "Mandats éligibles uniquement",
    refresh: "Rafraîchir",
    annonceCount: (n: number) => `${n} annonce${n > 1 ? "s" : ""}`,
    // ── Badges annonce
    badgePap: "Particulier",
    badgePro: "Pro",
    badgeBaissePrix: "Baisse de prix",
    badgeEligible: "Éligible mandat",
    badgeDpe: (note: string) => `DPE ${note}`,
    badgeAge: (h: number) => h < 24 ? `${h}h` : `${Math.floor(h / 24)}j`,
    // ── Carte annonce
    annonceVoir: "Voir l'annonce",
    annoncePrixM2: (v: number) => `${v.toLocaleString("fr-FR")} €/m²`,
    annonceSurface: (v: number) => `${v} m²`,
    annoncePieces: (v: number) => `${v} p.`,
    annoncePrix: (v: number) => `${Math.round(v / 1000)}k€`,
    annonceNoPhoto: "Aucune photo",
    annonceNoTitle: "Annonce sans titre",
    // ── Toolbar matching
    matchingHint: "Matchs générés par le moteur selon vos critères. Les alertes nécessitent une configuration provider.",
    matchGoodLabel: "Bon match",
    matchContactBtn: "Contacter",
    contactSoon: "Action « Contacter » bientôt disponible.",
    // ── Empty states annonces
    emptyAnnonces: "Aucune annonce disponible.",
    emptyAnnoncesTitle: "Aucune annonce scrappée",
    emptyAnnoncesText: "Les annonces sont importées automatiquement via les providers configurés (MoteurImmo, Apify…). Vérifiez les clés API dans les réglages.",
    emptyAnnoncesStep1: "Configurer les clés MoteurImmo / Apify",
    emptyAnnoncesStep2: "Lancer une mission « scraping annonces » dans l'onglet Swarms",
    emptyAnnoncesStep3: "Les nouvelles annonces apparaissent ici automatiquement",
    // ── Empty states matchs
    emptyMatchs: "Aucun match. Créez des critères acquéreur dans l'onglet Critères.",
    emptyMatchsTitle: "Aucun match calculé",
    emptyMatchsText: "Le moteur de matching compare chaque annonce aux critères de vos acquéreurs. Pour démarrer, créez au moins un profil acquéreur.",
    emptyMatchsStep1: "Aller dans l'onglet « Critères »",
    emptyMatchsStep2: "Créer un profil acquéreur avec budget, zones et surface",
    emptyMatchsStep3: "Le moteur calcule les matchs lors de la prochaine ingestion",
    // ── Empty states critères / acquéreurs
    emptyCriteres: "Aucun critère. Créez un profil acquéreur pour démarrer le matching.",
    emptyCriteresTitle: "Aucun acquéreur configuré",
    emptyCriteresText: "Ajoutez vos acquéreurs avec leurs critères de recherche. Le moteur leur envoie une alerte à chaque nouvelle annonce correspondante.",
    emptyCriteresStep1: "Cliquer sur « + Nouveau critère »",
    emptyCriteresStep2: "Renseigner les zones, le budget et la surface souhaitée",
    emptyCriteresStep3: "Activer les alertes email ou WhatsApp",
    // ── Degraded
    degradedAnnonces: "Module prospection indisponible : schéma ou migration manquante.",
    // ── Critères form
    criteresCount: (count: number) => `${count} critère${count > 1 ? "s" : ""} actif${count > 1 ? "s" : ""}`,
    newCritere: "+ Nouveau critère",
    critereNamePlaceholder: "Nom du critère (ex: Famille Martin)",
    critereZonesPlaceholder: "Zones (codes postaux séparés par virgule : 75011,75012)",
    budgetMaxPlaceholder: "Budget max (€)",
    surfaceMinPlaceholder: "Surface min (m²)",
    save: "Enregistrer",
    saving: "Enregistrement…",
    delete: "Supprimer",
    // ── Errors
    feedbackError: "Impossible d'enregistrer le feedback.",
    saveError: "Impossible d'enregistrer le critère.",
    deleteError: "Impossible de supprimer le critère.",
    loadAnnoncesError: "Impossible de charger les annonces.",
    loadMatchsError: "Impossible de charger les matchs.",
    loadCriteresError: "Impossible de charger les critères.",
    critereNameRequired: "Nom du critère requis.",
    // ── Accessibility labels
    emptyStepsAria: "Étapes pour démarrer",
    feedbackDislikeAria: "Je n'aime pas",
    feedbackLikeAria: "J'aime",
    // ── Spinner
    loading: "Chargement…",
    // ── Acquereurs table headers
    colNom: "Nom",
    colBudget: "Budget",
    colZones: "Zones",
    colContact: "Contact",
    colCriteres: "Critères",
    colAction: "Action",
    // ── Scrape personnalisé (Lot 2)
    scrapeBtn: "Lancer une prospection",
    scrapeModalTitle: "Prospection personnalisée",
    scrapeIntro: "Recherche des annonces selon vos critères, puis les confronte à vos acquéreurs actifs.",
    scrapeVille: "Ville ou code postal",
    scrapeVillePlaceholder: "Antibes, Cannes, 06600…",
    scrapeType: "Type de bien",
    scrapeTypeAppart: "Appartement",
    scrapeTypeMaison: "Maison",
    scrapeBudgetMin: "Budget min (€)",
    scrapeBudgetMax: "Budget max (€)",
    scrapeSurfaceMin: "Surface min (m²)",
    scrapeSurfaceMax: "Surface max (m²)",
    scrapePiecesMin: "Pièces min",
    scrapeMotsCles: "Mots-clés (séparés par virgule)",
    scrapeMotsClesPlaceholder: "terrasse, vue mer, sud…",
    scrapeSubmit: "Rechercher",
    scrapeSubmitting: "Recherche en cours…",
    scrapeCancel: "Fermer",
    scrapeVilleRequired: "Ville ou code postal requis.",
    scrapeNoProvider: "Aucun fournisseur d'annonces configuré (Apify/MoteurImmo). Ajoutez une clé pour lancer une recherche.",
    scrapeError: "La recherche a échoué. Réessayez.",
    scrapeResultTitle: "Résultats de la recherche",
    scrapeResultSummary: (scraped: number, kept: number, inserted: number) =>
      `${scraped} annonce${scraped > 1 ? "s" : ""} trouvée${scraped > 1 ? "s" : ""} · ${kept} retenue${kept > 1 ? "s" : ""} · ${inserted} nouvelle${inserted > 1 ? "s" : ""}`,
    scrapeResultMatched: (n: number) => `${n} match${n > 1 ? "s" : ""} avec vos acquéreurs`,
    scrapeResultEmpty: "Aucune annonce ne correspond à ces critères pour le moment. Élargissez la recherche ou réessayez plus tard.",
    scrapeTopMatchsTitle: "Meilleurs matchs",
    scrapeMatchLine: (nom: string, score: number) => `${nom} — score ${score}/100`,
    scrapeSeeAnnonces: "Voir les annonces",
    scrapeSeeMatchs: "Voir les matchs",
    // ── Criteres table headers
    colBudgetMax: "Budget Max",
    // ── Annonces table headers (legacy fallback)
    colAnnonce: "Annonce",
    colPrix: "Prix",
    colTags: "Tags",
    // ── Matching table headers
    colScore: "Score",
    colActions: "Actions",
  },
  mandates: {
    eyebrow: "Juridique",
    title: "Mandats",
    sub: "Vos mandats de vente — simple, exclusif, semi-exclusif.",
    newCta: "Nouveau mandat",
    empty: "Aucun mandat. Signez votre premier mandat.",
    delete: "Supprimer",
    cardTitle: "Mandat",
    noReference: "Sans référence",
    commissionUnit: " %",
    kpis: {
      total: "Mandats",
      active: "Actifs",
      underMandate: "Valeur sous mandat",
      avgCommission: "Commission moy.",
    },
    charts: {
      pipeline: "Pipeline",
      byKind: "Par type de mandat",
    },
    table: {
      reference: "Référence",
      price: "Prix",
      commission: "Commission",
      status: "Statut",
      kind: "Type",
      expires: "Expire",
      action: "",
    },
    statusLabels: {
      brouillon: "Brouillon",
      actif: "Actif",
      suspendu: "Suspendu",
      expire: "Expiré",
      resilie: "Résilié",
      realise: "Réalisé",
    } as Record<string, string>,
    kindLabels: {
      simple: "Simple",
      exclusif: "Exclusif",
      semi_exclusif: "Semi-exclusif",
    } as Record<string, string>,
    form: {
      title: "Mandat",
      property: "Bien",
      reference: "Référence",
      kind: "Type",
      askingPrice: "Prix affiché (€)",
      commissionPct: "Commission (%)",
      signedAt: "Signé le",
      expiresAt: "Expire le",
      save: "Enregistrer",
      cancel: "Annuler",
    },
    detail: {
      kicker: "Mandat",
      fallbackTitle: "Mandat sans titre",
      backLink: "‹ Mandats",
      cardMandat: "Détail du mandat",
      cardBien: "Bien lié",
      cardVisites: "Visites du bien",
      fields: {
        kind: "Type de mandat",
        reference: "Référence",
        askingPrice: "Prix affiché",
        commissionPct: "Commission",
        commissionAmount: "Montant commission",
        signedAt: "Signé le",
        expiresAt: "Expire le",
        daysLeft: (d: number) => `${d} jour${d !== 1 ? "s" : ""} restant${d !== 1 ? "s" : ""}`,
        daysExpired: "Expiré",
        notes: "Notes",
        updatedAt: "Dernière modif.",
      },
      expiringWarning: "Expire bientôt",
      wellLinked: "Voir la fiche bien",
      wellType: "Type",
      wellCity: "Ville",
      wellSurface: "Surface",
      wellPrice: "Prix affiché",
      wellStatus: "Statut",
      visitDate: "Date",
      visitContact: "Contact",
      emptyVisits: "Aucune visite planifiée pour ce bien.",
      emptyWell: "Aucun bien lié à ce mandat.",
    },
  },
  agenda: {
    eyebrow: "Agenda",
    title: "Agenda",
    sub: "Vue d'ensemble de vos visites à venir.",
    kpis: {
      thisWeek: "Cette semaine",
      today: "Aujourd'hui",
      toConfirm: "À confirmer",
    },
    locationSeparator: " — ",
  },
  profile: {
    eyebrow: "Compte",
    title: "Profil",
    sub: "Session active. Identité et périmètre d'accès.",
    identityTitle: "Identité",
    scopesTitle: "Scopes",
    sessionTitle: "Session",
    sessionHint: "Fermer la session sur cet appareil.",
    integrationsTitle: "Intégrations",
    integrationsHint: "Connectez vos services Google pour que l'assistant puisse les utiliser. Ce panneau ne fait que rendre visible et gérer les connexions existantes.",
    integrations: {
      loadError: "Impossible de récupérer l'état des intégrations. Réessayez.",
      notConfigured: "Intégrations indisponibles : la clé API Composio est absente côté serveur.",
      connected: "Connecté",
      disconnected: "Non connecté",
      notConfiguredBadge: "Non configuré",
      connect: "Connecter",
      connecting: "Connexion…",
      missingProviderConfig: "Configuration absente côté serveur pour ce service.",
      connectError: "Connexion impossible. Réessayez.",
      capabilitiesLabel: "Ce que ça permet",
      testInChat: "Testez-le dans le chat (« scanne mes emails »).",
      providers: {
        gmail: {
          name: "Gmail",
          description: "Lecture limitée de vos emails pour détecter les demandes d'estimation.",
          capabilities: [
            "Détecter les demandes d'estimation reçues par email",
            "Pré-remplir un brouillon d'estimation après votre confirmation",
          ],
        },
        calendar: {
          name: "Google Calendar",
          description: "Permettra à l'assistant de lire vos rendez-vous et vos disponibilités.",
          capabilities: [
            "Lire vos événements à venir",
            "Répondre à vos questions d'agenda dans le chat",
          ],
        },
      },
    },
    fields: {
      email: "Email",
      userId: "User ID",
      tenant: "Tenant",
      role: "Rôle",
      issued: "Session émise",
    },
    empty: "—",
  },
  login: {
    eyebrow: "Connexion",
    title: APP_NAME,
    sub: "Identifiants requis pour accéder au dashboard.",
    emailLabel: "Email",
    passwordLabel: "Mot de passe",
    submit: "Se connecter",
    submitBusy: "Connexion…",
    errors: {
      invalid_credentials: "Email ou mot de passe incorrect.",
      invalid_body: "Formulaire invalide.",
      supabase_not_configured: "Backend indisponible. Réessaie dans 1 min.",
      jwt_not_configured: "Backend mal configuré (JWT).",
      rate_limited: "Trop de tentatives. Réessaie dans 1 min.",
      generic: "Erreur de connexion.",
      network: "Erreur réseau.",
    } as Record<string, string>,
  },
  chat: {
    status: "Kimi K2.6",
    title: "Assistant",
    collapse: "Replier",
    reopen: "Chat",
    placeholder: "Message à Kimi…",
    empty: "Pose une question, ou « mémorise : … » pour enregistrer un fait du tenant.",
    userAvatar: "VO",
    assistantAvatar: "KI",
    errorPrefix: "Erreur",
  },
  common: {
    yes: "Oui",
    no: "Non",
    empty: "—",
    error: "Erreur",
    networkError: "Erreur réseau.",
    busy: "…",
    loading: "Chargement…",
    saving: "Enregistrement…",
    httpError: (status: number) => `Erreur ${status}`,
    required: (label: string) => `${label} requis`,
  },
  logout: "Se déconnecter",
  brochure: {
    docTitle: "Avis de valeur",
    iframeTitle: "Avis de valeur immobilière",
    openPdf: "Ouvrir le PDF",
    mobileHint: "Le document ne s'affiche pas ? Ouvrez-le directement :",
  },
  swarms: {
    eyebrow: "MySwarms",
    title: "Swarms",
    newCta: "Nouveau swarm",
    empty: "Aucun swarm configuré. Créez votre premier swarm pour automatiser vos analyses.",
    engineUnavailable: "Engine MySwarms non configuré ou indisponible.",
    engineFetchFailed: "Impossible de charger les swarms depuis l'engine.",
    kpis: {
      total: "Total",
      active: "Actifs",
      inactive: "Inactifs",
      runsToday: "Runs aujourd'hui",
    },
    statusActive: "Actif",
    statusInactive: "Inactif",
    agentCount: (n: number) => `${n} agent${n > 1 ? "s" : ""}`,
    taskCount: (n: number) => `${n} tâche${n > 1 ? "s" : ""}`,
    // Contextual panel (ValuationPanel)
    contextualTitle: "Analyse IA — MySwarms",
    contextualHint: "Lance un swarm Bienici pour enrichir l’analyse de marché avec des données en temps réel.",
    contextualLoading: "Chargement des swarms…",
    contextualEmpty: "Aucun swarm actif disponible.",
    contextualEngineError: "Engine MySwarms indisponible.",
    contextualCta: "Configurer un swarm",
    // Kickoff panel
    kickoffLaunch: (name: string) => `Lancer le swarm ${name}`,
    kickoffLaunching: "Lancement en cours…",
    kickoffRetry: "Réessayer",
    kickoffFailed: "Le swarm a échoué.",
    kickoffNetworkError: "Erreur réseau.",
    kickoffLaunchError: "Erreur lors du lancement.",
    // Steps
    stepsExpandLess: "Voir moins",
    stepsExpandMore: "Voir plus",
    // Run status badge labels
    runStatus: {
      pending: "En attente",
      running: "En cours...",
      done: "Terminé",
      failed: "Échoué",
      error: "Erreur",
      paused_hitl: "En attente d'un choix",
    },
    // Run detail breadcrumb / title
    runBreadcrumb: "Run",
    runTitle: "Run",
    // Dynamic list remove buttons (a11y)
    removeAgent: "Supprimer cet agent",
    removeTask: "Supprimer cette tâche",
    // Detail page
    runsTab: "Runs",
    agentsTab: "Agents & Tâches",
    configTab: "Configuration",
    runsHistory: "Historique des runs",
    runsEmpty: "Aucun run pour ce swarm.",
    runsRelaunch: "Relancer",
    runsRelaunching: "Lancement…",
    runsView: "Voir",
    confirmDelete: "Confirmer ?",
    confirmYes: "Oui",
    confirmNo: "Non",
    loadingError: "Erreur de chargement.",
    notFound: "Swarm introuvable.",
    runNotFound: "Run introuvable.",
    backToSwarms: "Retour aux swarms",
    backToSwarm: "Retour au swarm",
    runActive: "Analyse en cours…",
    runStepsTitle: "Étapes",
    runResultTitle: "Résultat",
    editTitle: "Modifier le swarm",
    editSave: "Sauvegarder",
    editSaving: "Sauvegarde…",
    editCancel: "Annuler",
    launchBtn: "Lancer",
    hideBtn: "Masquer",
    editBtn: "Éditer",
    deleteBtn: "Supprimer",
    launchPanelTitle: "Lancer le swarm",
    agentsCount: (n: number) => `Agents (${n})`,
    tasksCount: (n: number) => `Tâches (${n})`,
    toolsTitle: "Outils",
    agentsEmpty: "Aucun agent configuré.",
    tasksEmpty: "Aucune tâche configurée.",
    expectedOutputPrefix: "Résultat attendu : ",
    // New page
    newTitle: "Nouveau swarm",
    tabArchitect: "Architect (IA)",
    tabManual: "Manuel",
    architectTitle: "Décrire votre swarm en langage naturel",
    architectPlaceholder:
      "Ex : Un swarm qui analyse les annonces Bienici pour une ville donnée, extrait les prix au m², et produit un rapport de marché.",
    architectGenerateCta: "Générer la spec",
    architectGenerating: "Génération en cours…",
    architectSpecTitle: (name: string) => `Spec générée — ${name}`,
    architectCreateCta: "Créer ce swarm",
    architectCreating: "Création…",
    architectRegenCta: "Régénérer",
    architectHint: "Décris ton swarm à gauche : l'IA génère les agents et les tâches, prêts à créer en un clic.",
    architectJsonDetails: "Voir le JSON brut",
    architectSpecError: "La spec générée ne contient pas d'agents ou de tâches. Relancez la génération.",
    generateError: "Erreur lors de la génération.",
    createError: "Erreur lors de la création.",
    manualSectionGeneral: "Informations générales",
    metaName: "Nom",
    metaDescription: "Description",
    metaCreatedAt: "Créé le",
    manualNamePlaceholder: "Nom du swarm *",
    manualDescPlaceholder: "Description (optionnel)",
    manualSectionAgents: "Agents",
    manualAgentNamePlaceholder: "Nom de l’agent",
    manualAgentRolePlaceholder: "Rôle",
    manualAgentGoalPlaceholder: "Objectif (goal)",
    manualAddAgent: "+ Ajouter un agent",
    manualSectionTasks: "Tâches",
    manualTaskNamePlaceholder: "Nom de la tâche",
    manualTaskDescPlaceholder: "Description",
    manualTaskOutputPlaceholder: "Résultat attendu (expected_output)",
    manualAddTask: "+ Ajouter une tâche",
    manualNameRequired: "Le nom est requis.",
    manualCreateCta: "Créer",
    manualCreating: "Création…",
    runLaunchedAt: (date: string) => `Lancé le ${date}`,
    runRelaunching: "Lancement…",
    runRelaunchCta: "Relancer",
    reportSelectHint: "Sélectionne un run ci-dessus pour afficher son rapport.",
    reportTechnicalDetails: "Détails techniques (étapes des agents)",
    reportEmpty: "Ce run n'a pas encore produit de rapport.",
    reportTokens: "tokens",
    reportDurationUnit: "s",
  },
} as const;
