/**
 * Strings UI centralisées (point d'entrée i18n futur).
 * Aucun texte visible utilisateur ne doit être hardcodé dans les composants —
 * tout passe par cet objet. Les clés techniques (ids, routes, classNames) restent inline.
 */
export const APP_NAME = "Azigo";

export const UI = {
  app: {
    name: APP_NAME,
    description: `${APP_NAME} — Cockpit`,
  },
  nav: {
    home: "Accueil",
    estimations: "Estimations",
    properties: "Biens",
    leads: "Leads",
    visits: "Visites",
    mandates: "Mandats",
    agenda: "Agenda",
    prospection: "Prospection",
    portefeuille: "Portefeuille",
    clients: "Clients",
    agents: "Agents",
    radar: "Radar",
    approvals: "Approbations",
    outbox: "Outbox",
    offmarket: "Off-market",
    actionCenter: "Centre d'actions",
    reactivation: "Réactivation",
    conversion: "Conversion",
    renewal: "Renouvellements",
    assistant: "Assistant",
    profile: "Profil",
    admin: "Admin",
    /** Libellé accessible de la sous-nav de groupe (SubNav). */
    sections: "Sections",
  },
  admin: {
    eyebrow: "Interne",
    title: "Admin",
    sub: "Santé des providers, volumétrie, observabilité — lecture seule.",
    providersTitle: "Providers",
    configured: "Configuré",
    absent: "Absent",
    countsTitle: "Volumétrie",
    estimations: "Estimations",
    leads: "Leads",
    leadsEnriched: "Leads enrichis",
    providersConfigured: "Providers configurés",
    obsTitle: "Observabilité",
    obsBody: "Erreurs → Sentry · Coûts/latence LLM → Langfuse (consoles externes).",
    jobsTitle: "Jobs",
    jobsPlaceholder: "Jobs asynchrones — disponible une fois l'async PDF activé.",
    degraded: "Base de données indisponible.",
  },
  /** Libellés partagés des composants viz (Funnel, BarList, Donut, DataTable). */
  viz: {
    empty: "Pas encore de données",
    edit: "Modifier",
    delete: "Supprimer",
    open: "Ouvrir",
    actions: "Actions",
  },
  dashboard: {
    eyebrow: "Cockpit",
    title: "Aujourd'hui",
    /** Centre d'actions — « Que faire maintenant, pour qui, pourquoi ? ». */
    center: {
      title: "À traiter maintenant",
      subtitle: (n: number) =>
        n === 0
          ? "Rien en attente — tout est à jour."
          : `${n} action${n > 1 ? "s" : ""} prioritaire${n > 1 ? "s" : ""}, la plus urgente en premier.`,
      filterAll: "Tout",
      empty: "Rien à traiter pour l'instant.",
      emptyHint: "Les relances, RDV et opportunités apparaîtront ici dès qu'il y en a.",
      /** Libellés de catégorie (clés = ActionCategory). */
      groups: {
        overdue: "En retard",
        today: "Aujourd'hui",
        task: "Mes tâches",
        validation: "À valider",
        rdv: "Rendez-vous",
        relance: "Relances",
        proprietaire: "Propriétaires",
        mandat: "Mandats à saisir",
        estimation: "Estimations à reprendre",
        acquereur: "Acquéreurs à servir",
        match: "Matchs à examiner",
      } as Record<string, string>,
      /** Actions rapides. */
      quick: {
        call: "Appeler",
        message: "Message",
        schedule: "Planifier",
        open: "Ouvrir",
        done: "Traité",
        snooze: "Reporter",
        validate: "Valider",
      },
      /** Raisons métier (POURQUOI), injectées dans la dérivation. */
      reasons: {
        staleFor: (days: number) => `Non recontacté depuis ${days} j`,
        visitWith: (who: string) => `Visite avec ${who}`,
        rdvOn: "Rendez-vous à venir",
        estimationResume: "Estimation à finaliser",
        acquereurNoProposal: "Acquéreur sans proposition récente",
        matchToReview: (score: number) => `Match à examiner · score ${score}`,
        proprietaireToCall: "Propriétaire à rappeler",
        mandateDraft: "Mandat en brouillon à finaliser",
        taskDue: "Tâche du jour",
        taskOverdue: "Tâche en retard",
        taskOpen: "À faire",
        validationNeeded: "Validation demandée",
      },
      fallback: {
        lead: "Contact sans nom",
        property: "Bien non renseigné",
        estimation: "Estimation",
        mandate: "Mandat",
        critere: "Recherche acquéreur",
      },
      /** Titres/notes des tâches créées par une action rapide. */
      messageTaskTitle: (who: string) => `Message à envoyer à ${who}`,
      messageTaskNote: "Brouillon à rédiger — aucun envoi automatique (à faire manuellement).",
      validationTaskTitle: (who: string) => `Validation à obtenir — ${who}`,
      /** Retours après action (statut). */
      notices: {
        done: "Marqué comme traité.",
        snoozed: "Reporté à demain.",
        messageDrafted: "Tâche « message à envoyer » créée (brouillon, non envoyé).",
        validationRequested: "Demande de validation enregistrée.",
      },
    },
    kpis: {
      properties: "Biens",
      activeLeads: "Leads actifs",
      upcomingVisits: "Visites à venir",
      activeMandates: "Mandats actifs",
    },
    today: {
      title: "À faire maintenant",
      visitsLabel: "Visites sous 48 h",
      mandatesLabel: "Mandats à renouveler",
      emptyVisits: "Aucune visite planifiée.",
      emptyMandates: "Aucun mandat n'expire bientôt.",
      seeAll: "Tout voir",
    },
    opportunities: {
      title: "Opportunités",
      estimationsLabel: "Estimations en cours",
      estimationsHint: "Mandats potentiels",
      emptyEstimations: "Aucune estimation en cours.",
      leadsLabel: "Leads à relancer",
      leadsHint: "Contacts à réactiver",
      emptyLeads: "Aucun lead à relancer.",
    },
    actions: {
      title: "Actions rapides",
      newEstimation: "Nouvelle estimation",
      newEstimationDesc: "Entretien vendeur guidé, avis de valeur en quelques minutes.",
      newProperty: "Nouveau bien",
      newClient: "Nouveau client",
      newVisit: "Nouvelle visite",
      launchPros: "Lancer une prospection",
      create: "Créer",
    },
    // Legacy keys kept for backwards compat
    priorities: {
      title: "Actions CRM",
      body: "Les mêmes volumes restent visibles dans le header ; ici, on garde seulement les chemins d'action.",
      leadsEyebrow: "Pipeline",
      leadsTitle: "Leads",
      leadsBody: "Qualifier, relancer et faire avancer les contacts ouverts.",
      visitsEyebrow: "Agenda",
      visitsTitle: "Visites",
      visitsBody: "Préparer les rendez-vous et vérifier les biens liés.",
      mandatesEyebrow: "Mandats",
      mandatesTitle: "Mandats",
      mandatesBody: "Suivre les mandats signés, échéances et statuts.",
      openPipeline: "Traiter",
      prepareVisits: "Préparer",
      reviewMandates: "Piloter",
    },
    commands: {
      title: "Actions rapides",
      visualAria: "Raccourcis d'action du cockpit",
      visualEyebrow: "Console",
      visualTitle: "Scraper · screener · relever · rechercher",
      visualBody: "Accès direct aux moteurs.",
      scrapeEyebrow: "Scraper",
      scrapeTitle: "Annonces",
      scrapeBody: "Ouvrir le flux des annonces ingérées et rafraîchir la lecture marché.",
      screenEyebrow: "Screener",
      screenTitle: "Matching",
      screenBody: "Voir les scores acquéreur ↔ annonce et prioriser les contacts.",
      releveEyebrow: "Relever",
      releveTitle: "Critères",
      releveBody: "Créer ou mettre à jour les profils acquéreurs à surveiller.",
      searchEyebrow: "Rechercher",
      searchTitle: "Mission",
      searchBody: "Préremplir une mission de recherche rapide depuis le cockpit.",
      searchObjective: "Recherche rapidement les meilleures opportunités immobilières à traiter aujourd'hui et propose les 3 actions prioritaires.",
      open: "Ouvrir",
      launch: "Préparer",
    },
    quick: {
      title: "Raccourcis métier",
      propertiesEyebrow: "Portefeuille",
      propertiesTitle: "Biens",
      propertiesBody: "Ouvrir le portefeuille et les fiches détaillées.",
      estimateEyebrow: "Valeur",
      estimateTitle: "Nouvelle estimation",
      estimateBody: "Démarrer un avis de valeur guidé par l'IA.",
      prospectionEyebrow: "Acquisition",
      prospectionTitle: "Prospection",
      prospectionBody: "Voir les annonces, critères acquéreurs et matchs.",
      missionsEyebrow: "IA",
      missionsTitle: "Mission",
      missionsBody: "Lancer une mission agentique en langage naturel.",
      open: "Ouvrir",
      launch: "Lancer",
    },
    portfolioPanel: {
      title: "Accès rapide",
      actions: {
        properties: "Biens",
        leads: "Leads",
        visits: "Visites",
        mandates: "Mandats",
      },
      open: "Ouvrir",
    },
    propertiesEmpty: "Aucun bien pour le moment.",
    addProperty: "Ajouter un bien",
    seeAllProperties: "Voir tous les biens",
    recentPortfolio: "Portefeuille récent",
    charts: {
      pipeline: "Pipeline estimations",
      byCity: "Répartition par ville",
      byValueBand: "Valeur estimée par tranche",
      completion: "Taux de complétion",
      completionSub: "Prêtes",
      heatmap: "Estimations par ville et statut",
    },
    heatmapNoCity: "Sans ville",
    table: {
      property: "Bien",
      status: "Statut",
      value: "Valeur",
      type: "Type",
      city: "Ville",
      updated: "Maj",
      action: "",
    },
    recent: "Estimations récentes",
    seeAll: "Voir toutes les estimations",
    activity: "Activité récente",
    activityEmpty: "Aucune visite planifiée.",
    visitBadge: "Visite",
    propertyLinked: "Bien lié",
    propertyMissing: "Bien non renseigné",
    heroMeta: (n: number) =>
      `${n} estimation${n > 1 ? "s" : ""} suivie${n > 1 ? "s" : ""}`,
    donutMeta: (ready: number, total: number) =>
      `${ready} prête${ready > 1 ? "s" : ""} sur ${total}`,
    kpiHints: {
      properties: "Au portefeuille",
      activeLeads: "En cours",
      upcomingVisits: "Planifiées",
      activeMandates: "Signés actifs",
    },
    cards: {
      assistantTitle: "Assistant",
      assistantBody:
        "Le rail droit exécute l'assistant IA (streaming, persisté par utilisateur et tenant). Tape « mémorise : … » pour enregistrer un fait partagé du tenant, réinjecté au prochain message.",
    },
  },
  estimations: {
    eyebrow: "Cockpit",
    title: "Estimations",
    sub: "Vos avis de valeur — entretien guidé, analyse marché, brochure.",
    newCta: "Nouvelle estimation",
    empty: "Aucune estimation pour le moment. Démarrez votre premier avis de valeur.",
    kpis: {
      total: "Estimations",
      ready: "Prêtes",
      inProgress: "En cours",
      avgValue: "Valeur moy. (prêtes)",
    },
    charts: {
      pipeline: "Pipeline",
      byType: "Par type de bien",
    },
    table: {
      location: "Bien",
      type: "Type",
      value: "Valeur",
      status: "Statut",
      updated: "Maj",
      action: "",
    },
    back: "Retour aux estimations",
    backToProperty: "Retour au bien",
    interviewTitle: "Entretien",
    interviewSub: "Décrivez votre bien en quelques mots — l'assistant ne demande que l'essentiel, dans l'ordre.",
    soon: "Bientôt — le moteur d'entretien arrive.",
    interviewUnavailable:
      "Assistant momentanément indisponible. Réessayez, ou continuez : les informations déjà collectées suffisent à lancer l'estimation dès que l'essentiel est réuni.",
    generate: "Générer l'estimation",
    generating: "Calcul de l'estimation…",
    creating: "Création…",
    createError: "Erreur lors de la création.",
    downloadPdf: "Télécharger le PDF",
    share: "Partager",
    valuationTitle: "Estimation",
    low: "Fourchette basse",
    market: "Valeur de marché",
    high: "Fourchette haute",
    perSqm: "Prix au m²",
    perSqmUnit: " / m²",
    surfaceUnit: " m²",
    recommended: "Prix de mise en vente conseillé",
    adjustmentsTitle: "Ajustements",
    marketContextTitle: "Contexte marché",
    marketContextCta: "Charger le contexte marché",
    marketContextLoading: "Recherche en cours…",
    marketContextEmpty: "Contexte marché indisponible pour le moment.",
    marketContextSources: "Sources",
    marketContextHint: "Informations de contexte — n'entrent pas dans le calcul du prix.",
    adjustSeparator: " — ",
    premiumSign: "+",
    discountSign: "−",
    strategiesTitle: "Stratégies de vente",
    shareCopied: "Lien copié",
    fallbackName: "Estimation",
    resume: "Reprendre",
    open: "Ouvrir",
    ficheTitle: "Fiche bien",
    ficheEmpty: "Les champs se remplissent au fil de l'entretien.",
    toConfirm: "à confirmer",
    blockProgress: (n: number, total: number) => `Bloc ${n} / ${total}`,
    keyInfoProgress: (n: number, total: number) => `${n} / ${total} infos clés`,
    nextInfo: (label: string) => `Prochaine info : ${label}`,
    allKeyInfo: "Infos clés réunies",
    readyToGenerate: "Prêt à générer l'estimation",
    listingComparablesTitle: "Annonces en cours",
    listingComparablesLink: "Voir l'annonce",
    listingComparablesEmpty: "Aucune annonce comparable trouvée pour ce bien.",
    sectorMapTitle: "Biens à vendre autour",
    sectorMapAttribution: "© OpenStreetMap",
    sectorMapLegend: "Le bien · biens à vendre alentour",
    sectorMapEmpty: "Localisation des annonces indisponible pour la carte du secteur.",
    listingPhotoAlt: "Photo de l'annonce",
    listingColAnnonce: "Annonce",
    listingColSource: "Source",
    listingColPrix: "Prix",
    listingColSurface: "Surface",
    listingColPrixM2: "Prix / m²",
    listingColActions: "",
    listingSourceLabels: {
      leboncoin: "LeBonCoin",
      bienici: "Bienici",
    } as Record<string, string>,
    listingFetchSourceLabels: {
      apify: "LeBonCoin",
      myswarms: "Bienici",
      none: "Marché local",
    } as Record<string, string>,
    listingFetchSourcePrefix: "Source annonces :",
    confidenceLabels: {
      indicative: "Indicative",
      moyenne: "Moyenne",
      elevee: "Élevée",
    } as Record<string, string>,
    confidenceTooltips: {
      indicative: "Estimation basée sur peu de données de marché — fourchette large.",
      moyenne: "Estimation avec données DVF partielles — bonne fiabilité.",
      elevee: "Estimation robuste, nombreux comparables DVF récents.",
    } as Record<string, string>,
    comparablesDvf: (n: number) => `${n} comparable${n > 1 ? "s" : ""} DVF`,
    recoPriceLabel: "Conseillé",
    // ── Identité du bien (hero résultat) ──
    typeLabels: {
      appartement: "Appartement",
      maison: "Maison",
      immeuble: "Immeuble",
      local_commercial: "Local commercial",
      terrain: "Terrain",
      autre: "Bien",
    } as Record<string, string>,
    rangeLabel: "Fourchette d'estimation",
    dpeBadge: (c: string) => `DPE ${c}`,
    // ── Provenance & fiabilité (défendable face au vendeur) ──
    provenanceTitle: "Base de l'estimation",
    basedOnComparables: (n: number) =>
      `Fondé sur ${n} comparable${n > 1 ? "s" : ""} de vente réelle`,
    dataStatusLabels: {
      complete: "Données complètes",
      partial: "Données partielles",
      degraded: "Données limitées",
    } as Record<string, string>,
    dataStatusTooltips: {
      complete: "Comparables nombreux, proches et récents — socle solide.",
      partial: "Comparables suffisants mais dispersés ou plus anciens.",
      degraded: "Peu de comparables exploitables — fourchette élargie.",
    } as Record<string, string>,
    medianPriceLabel: "Prix médian secteur",
    trendLabel: "Tendance",
    trendLabels: {
      hausse: "En hausse",
      stable: "Stable",
      baisse: "En repli",
    } as Record<string, string>,
    radiusLabel: (km: number) =>
      `Rayon moyen ${km.toLocaleString("fr-FR", { maximumFractionDigits: 1 })} km`,
    recencyLabel: (mois: number) => `Récence ${Math.round(mois)} mois`,
    dispersionLabel: (pct: number) => `Dispersion ${Math.round(pct)} %`,
    transactions12m: (n: number) => `${n} vente${n > 1 ? "s" : ""} / 12 mois`,
    // ── Comparables DVF (ventes réelles, socle du calcul) ──
    dvfTitle: "Ventes réelles comparables",
    dvfSubtitle: "Transactions officielles du secteur — socle de l'estimation.",
    dvfColDate: "Date",
    dvfColType: "Type",
    dvfColSurface: "Surface",
    dvfColPrice: "Prix",
    dvfColPerM2: "€ / m²",
    dvfEmpty: "Aucune vente comparable disponible pour ce secteur.",
    dvfSourceNote: (n: number) =>
      `${n} transaction${n > 1 ? "s" : ""} analysée${n > 1 ? "s" : ""} · DVF Etalab · géolocalisées`,
    dvfPieces: (n: number) => `${n} p.`,
    // ── Continuité (actions post-estimation, routes vérifiées) ──
    nextStepsTitle: "Poursuivre",
    createProperty: "Créer la fiche du bien",
    openProperty: "Ouvrir la fiche du bien",
    prepareMandate: "Préparer un mandat",
    generatingTitle: "Analyse en cours…",
    generatingSub: "Nous interrogeons les bases DVF, DPE et les annonces du marché.",
    generatingSteps: [
      "Géocodage",
      "Cadastre",
      "Sections cadastrales",
      "Mutations DVF",
      "DPE",
      "Comparables",
      "Valorisation",
      "Annonces comparables",
      "Finalisation",
    ],
    status: {
      draft: "Brouillon",
      interviewing: "Entretien en cours",
      recap: "Récapitulatif",
      valuating: "Calcul",
      ready: "Prête",
      archived: "Archivée",
    } as Record<string, string>,
    // Libellés courts (colonnes de la heatmap dashboard).
    statusShort: {
      draft: "Brn",
      interviewing: "Entr.",
      recap: "Récap",
      valuating: "Calc.",
      ready: "Prête",
      archived: "Arch.",
    } as Record<string, string>,
    // ── Continuité commerciale (estimation → propriétaire → mandat → décision) ──
    continuity: {
      title: "Suite commerciale",
      subtitle:
        "L'estimation est le point de départ : rattachez le propriétaire, ouvrez l'opportunité, suivez la décision.",
      // Pipeline (4 jalons)
      pipelineOwner: "Propriétaire",
      pipelineOpportunity: "Opportunité",
      pipelineDecision: "Décision",
      pipelineEstimation: "Estimation",
      stepDone: "Fait",
      stepTodo: "À faire",
      // ── Propriétaire (lead vendeur) ──
      ownerTitle: "Propriétaire",
      ownerNone: "Aucun propriétaire rattaché à cette estimation.",
      ownerAttachCta: "Rattacher un propriétaire",
      ownerCreateCta: "Créer le propriétaire",
      ownerLinkCta: "Rattacher ce propriétaire",
      ownerModeCreate: "Nouveau propriétaire",
      ownerModeLink: "Propriétaire existant",
      ownerPickLabel: "Choisir un propriétaire (vendeur)",
      ownerPickPlaceholder: "Sélectionner…",
      ownerLinkEmpty: "Aucun propriétaire vendeur enregistré — créez-en un.",
      ownerCancel: "Annuler",
      ownerOpen: "Ouvrir la fiche",
      ownerNameLabel: "Nom du propriétaire",
      ownerNamePlaceholder: "Nom et prénom",
      ownerEmailLabel: "Email",
      ownerEmailPlaceholder: "email (optionnel)",
      ownerPhoneLabel: "Téléphone",
      ownerPhonePlaceholder: "téléphone (optionnel)",
      ownerNotesLabel: "Note",
      ownerNotesPlaceholder: "Contexte du contact (optionnel)",
      ownerKindBadge: "Vendeur",
      ownerCreating: "Rattachement…",
      ownerError: "Le rattachement du propriétaire a échoué. Réessayez.",
      ownerNameRequired: "Renseignez le nom du propriétaire.",
      ownerLinkedNote: "Lead vendeur créé dans le CRM (statut Nouveau).",
      // ── Opportunité de mandat ──
      mandateTitle: "Opportunité de mandat",
      mandateNone: "Aucune opportunité ouverte.",
      mandateHint:
        "Ouvre un mandat au brouillon lié au bien, au prix conseillé — à finaliser côté mandats.",
      mandateCreateCta: "Créer l'opportunité de mandat",
      mandateCreating: "Création…",
      mandateOpen: "Ouvrir le mandat",
      mandateError: "La création de l'opportunité a échoué. Réessayez.",
      mandateDraftBadge: "Brouillon",
      mandateStatusLabel: "Statut",
      mandateAskingLabel: "Prix demandé",
      mandateKindLabel: "Type de mandat",
      mandateKinds: {
        simple: "Simple",
        exclusif: "Exclusif",
        semi_exclusif: "Semi-exclusif",
      } as Record<string, string>,
      // ── Décision & prochaine action ──
      decisionTitle: "Décision",
      decisionLabel: "Statut de la décision",
      decisionNone: "Non décidé",
      decisions: {
        en_attente: "En attente",
        a_relancer: "À relancer",
        mandat_signe: "Mandat signé",
        refuse: "Refusé",
        perdu: "Perdu",
      } as Record<string, string>,
      nextActionTitle: "Prochaine action",
      nextActionLabel: "Prochaine action commerciale",
      nextActionPlaceholder: "Ex : rappeler le propriétaire jeudi, envoyer l'avis de valeur…",
      nextActionEmpty: "Aucune action planifiée.",
      saveCta: "Enregistrer",
      saving: "Enregistrement…",
      saved: "Enregistré",
      saveError: "Enregistrement impossible. Réessayez.",
      // ── Ajustements : lecture combinée (calculé vs saisi vs manquant vs à vérifier) ──
      adjustClarityTitle: "Composition de la valeur",
      adjustClaritySubtitle:
        "Ce qui est calculé par le moteur, ce que vous avez saisi, ce qui manque ou reste à vérifier.",
      adjustCalculatedTitle: "Calculé par le moteur",
      adjustCalculatedHint: "Ajustements dérivés des comparables DVF.",
      adjustCalculatedEmpty: "Aucun ajustement automatique retenu.",
      adjustManualTitle: "Saisi manuellement",
      adjustManualHint: "Vos ajustements, avec justification et auteur.",
      adjustManualEmpty: "Aucun ajustement manuel pour le moment.",
      adjustMissingTitle: "Manquant",
      adjustMissingHint: "Informations non renseignées qui élargissent la fourchette.",
      adjustMissingEmpty: "Rien d'essentiel ne manque.",
      adjustVerifyTitle: "À vérifier",
      adjustVerifyHint: "Données déclarées à confirmer avant l'avis définitif.",
      adjustVerifyEmpty: "Aucune donnée en attente de vérification.",
      // Légende des 4 natures (badges)
      legendCalculated: "Calculé",
      legendManual: "Saisi",
      legendMissing: "Manquant",
      legendVerify: "À vérifier",
      // ── Ajout d'un ajustement manuel ──
      addAdjustmentCta: "Ajouter un ajustement manuel",
      adjustFormTitle: "Ajustement manuel",
      adjustFormHint:
        "Un motif d'ajustement qui n'est pas dans le calcul automatique (négociation, urgence, défaut connu…).",
      adjustLabelLabel: "Libellé",
      adjustLabelPlaceholder: "Ex : Travaux toiture à prévoir",
      adjustUnitLabel: "Type d'ajustement",
      adjustUnitPct: "Pourcentage",
      adjustUnitEur: "Montant (€)",
      adjustValueLabel: "Valeur",
      adjustValuePctPlaceholder: "Ex : -5 (négatif = décote)",
      adjustValueEurPlaceholder: "Ex : -15000",
      adjustRaisonLabel: "Justification",
      adjustRaisonPlaceholder: "Pourquoi cet ajustement ?",
      adjustSaveCta: "Ajouter",
      adjustSaving: "Ajout…",
      adjustCancel: "Annuler",
      adjustRemove: "Retirer",
      adjustRemoving: "Retrait…",
      adjustValueRequired: "Renseignez un pourcentage OU un montant, non nul.",
      adjustLabelRequired: "Renseignez un libellé.",
      adjustRaisonRequired: "Renseignez une justification.",
      adjustError: "Action impossible. Réessayez.",
      adjustAuthorPrefix: "par",
      adjustCalcTag: "moteur",
      whatNextTitle: "Quoi faire ensuite",
    },
  },
  properties: {
    eyebrow: "Portefeuille",
    title: "Biens",
    sub: "Votre portefeuille de biens — du prospect à la vente.",
    newCta: "Nouveau bien",
    empty: "Aucun bien. Ajoutez votre premier mandat ou prospect.",
    open: "Ouvrir",
    delete: "Supprimer",
    fallbackTitle: "Bien sans titre",
    statusAria: "Statut du bien",
    statusUpdateError: "Le statut n'a pas pu être mis à jour. Réessayez.",
    cardCaracteristiques: "Caractéristiques",
    seeEstimation: "Voir l'estimation",
    estimateThisProperty: "Estimer ce bien",
    fields: {
      type: "Type",
      surface: "Surface",
      rooms: "Pièces",
      bedrooms: "Chambres",
      address: "Adresse",
      postalCode: "Code postal",
      estimation: "Estimation liée",
    },
    kpis: {
      total: "Biens",
      forSale: "En vente",
      sold: "Vendus",
      portfolio: "Valeur portefeuille",
    },
    charts: {
      pipeline: "Pipeline",
      soldRate: "Taux de vente",
      soldRateSub: "Vendus",
      byType: "Par type de bien",
      byValueBand: "Prix affiché par tranche",
    },
    table: {
      title: "Bien",
      type: "Type",
      city: "Ville",
      surface: "Surface",
      price: "Prix",
      status: "Statut",
      action: "",
    },
    statusLabels: {
      prospect: "Prospect",
      estimation: "En estimation",
      mandat: "Mandat",
      en_vente: "En vente",
      sous_offre: "Sous offre",
      vendu: "Vendu",
      archive: "Archivé",
    } as Record<string, string>,
    typeLabels: {
      appartement: "Appartement",
      maison: "Maison",
      terrain: "Terrain",
      local: "Local",
      autre: "Autre",
    } as Record<string, string>,
    form: {
      title: "Bien",
      sectionMain: "Informations principales",
      sectionLocation: "Localisation",
      sectionFeatures: "Caractéristiques",
      sectionPrice: "Prix / mandat",
      name: "Titre",
      type: "Type",
      address: "Adresse",
      city: "Ville",
      postalCode: "Code postal",
      surface: "Surface (m²)",
      rooms: "Pièces",
      bedrooms: "Chambres",
      askingPrice: "Prix affiché (€)",
      notes: "Notes",
      save: "Enregistrer",
      cancel: "Annuler",
      dpeLabel: "DPE (A à G)",
      gesLabel: "GES (A à G)",
      yearBuilt: "Année de construction",
      floor: "Étage",
      floorTotal: "Nb étages total",
      orientation: "Orientation",
      chargesMonthly: "Charges mensuelles (€/mois)",
      taxeFonciere: "Taxe foncière (€/an)",
      hasParking: "Parking",
      hasElevator: "Ascenseur",
      hasGarden: "Jardin",
      hasTerrace: "Terrasse",
      hasPool: "Piscine",
      hasCellar: "Cave",
      parkingCount: "Nombre de places de parking",
    },
    dpe: {
      title: "Performance énergétique",
      label: "DPE",
      gesLabel: "GES",
      letters: { A: "A", B: "B", C: "C", D: "D", E: "E", F: "F", G: "G" } as Record<string, string>,
      none: "Non renseigné",
    },
    enrichissement: {
      title: "Informations complémentaires",
      yearBuilt: "Année de construction",
      floor: "Étage",
      floorTotal: "Nb étages",
      orientation: "Orientation",
      charges: "Charges mensuelles",
      taxeFonciere: "Taxe foncière",
      parking: "Parking",
      elevator: "Ascenseur",
      garden: "Jardin",
      terrace: "Terrasse",
      pool: "Piscine",
      cellar: "Cave",
      parkingCount: "Nb places parking",
      yes: "Oui",
      no: "Non",
    },
    photos: {
      title: "Photos",
      altFallback: "Bien immobilier",
      upload: "Ajouter des photos",
      uploading: "Upload en cours…",
      empty: "Aucune photo. Glissez-déposez ou cliquez pour en ajouter.",
      delete: "Supprimer",
      cover: "Couverture",
      error: "Erreur lors de l'upload.",
      invalidType: "Format non supporté (JPEG, PNG, WebP uniquement).",
      tooLarge: "Fichier trop volumineux (max 10 Mo).",
    },
    editBtn: "Modifier le bien",
    newVisitBtn: "Nouvelle visite",
    newMandateBtn: "Nouveau mandat",
    daysOnMarket: (d: number) => `${d} jour${d > 1 ? "s" : ""} au portefeuille`,
    // ── Vue cockpit portefeuille (par défaut)
    cockpit: {
      panelTitle: "Votre portefeuille",
      tabCockpit: "Cockpit",
      tabKanban: "Kanban",
      tabList: "Liste",
      active: "En vente / actifs",
      toComplete: "À compléter",
      recent: "Récemment ajoutés",
      closed: "Vendus / archivés",
      recentActivity: "Activité récente",
      zoneEmpty: "Rien pour l'instant",
      seeMandates: "Voir les mandats",
      seeEstimations: "Voir les estimations",
      healthTitle: "Signaux portefeuille",
      healthNoPrix: "sans prix",
      healthNoCity: "sans ville",
      healthNoType: "sans type",
      live: "● Session live",
      liveUpdated: "● Mis à jour",
      liveRefreshing: "↻ Actualisation…",
      liveHint: "Synchronisation entre les onglets de ce navigateur (intra-session).",
    },
    // Fiche détail premium
    detail: {
      cardPhotos: "Photos",
      cardCaracteristiques: "Caractéristiques",
      cardEquipements: "Équipements & prestations",
      cardLocalisation: "Localisation",
      cardDpe: "Performance énergétique",
      cardNotes: "Notes internes",
      cardLeads: "Leads intéressés",
      cardVisites: "Visites planifiées",
      cardMandats: "Mandats",
      heroPriceSuffix: "",
      pricePerSqm: (v: string) => `${v} / m²`,
      priceType: { asking: "Prix affiché", estimated: "Valeur estimée" } as Record<string, string>,
      chipSurface: (v: number) => `${v} m²`,
      chipRooms: (n: number) => `${n} pièce${n > 1 ? "s" : ""}`,
      chipBedrooms: (n: number) => `${n} chambre${n > 1 ? "s" : ""}`,
      chipFloor: (f: number, t: number | null | undefined) =>
        t != null ? `Étage ${f}/${t}` : `Étage ${f}`,
      gridYearBuilt: "Construit en",
      gridOrientation: "Orientation",
      gridCharges: "Charges",
      gridChargesSuffix: "/ mois",
      gridTaxe: "Taxe foncière",
      gridTaxeSuffix: "/ an",
      gridParking: "Parking",
      gridParkingPlaces: (n: number) => `${n} place${n > 1 ? "s" : ""}`,
      gridEstimation: "Estimation liée",
      gridUpdated: "Dernière modif.",
      equipElevator: "Ascenseur",
      equipParking: "Parking",
      equipGarden: "Jardin",
      equipTerrace: "Terrasse",
      equipPool: "Piscine",
      equipCellar: "Cave",
      locMapsLink: "Voir sur Google Maps",
      dpeNote: (l: string) => `Classe ${l}`,
      gesNote: (l: string) => `Classe ${l}`,
      notesEmpty: "Aucune note.",
      leadsEmpty: "Aucun lead associé.",
      visitsEmpty: "Aucune visite planifiée.",
      mandatesEmpty: "Aucun mandat.",
      seeAllLeads: "Voir tous les leads →",
      visitDuration: (m: number) => `${m} min`,
      mandateRef: "Sans référence",
      commission: (p: number) => `${p}%`,
    },
  },
  leads: {
    eyebrow: "Commercial",
    title: "Leads",
    sub: "Votre pipeline commercial — acheteurs et vendeurs.",
    newCta: "Nouveau lead",
    empty: "Aucun lead. Ajoutez votre premier contact.",
    delete: "Supprimer",
    // ── Vue cockpit relationnel (par défaut)
    cockpit: {
      panelTitle: "Vos clients",
      tabCockpit: "Cockpit",
      tabKanban: "Kanban",
      tabList: "Liste",
      toFollow: "À relancer",
      fresh: "Nouveaux leads",
      hotSellers: "Vendeurs chauds",
      activeBuyers: "Acquéreurs actifs",
      recentActivity: "Activité récente",
      zoneEmpty: "Rien pour l'instant",
    },
    statusUpdateError: "Le statut n'a pas pu être mis à jour. Réessayez.",
    fallbackInitials: "—",
    enrich: "Enrichir",
    enriching: "Enrichissement…",
    enrichDone: "Lead enrichi.",
    enrichNoData: "Aucune donnée exploitable trouvée.",
    enrichConsent:
      "Confirmer l'enrichissement B2B via un data broker externe ? À utiliser uniquement pour un contact professionnel avec base légale.",
    enrichErrors: {
      consent_required: "Consentement RGPD requis.",
      forbidden_particulier: "Enrichissement interdit pour un particulier.",
      invalid_body: "Demande d'enrichissement invalide.",
      no_email_to_enrich: "Un email est requis pour enrichir ce lead.",
      enrichment_not_configured: "Aucun provider d'enrichissement n'est configuré.",
      rate_limited: "Trop d'enrichissements. Réessayez dans un instant.",
      not_found: "Lead introuvable.",
    } as Record<string, string>,
    cardTitle: "Leads intéressés",
    seeAll: "Voir tous les leads",
    kpis: {
      total: "Leads",
      active: "Actifs",
      won: "Gagnés",
      conversion: "Conversion",
    },
    charts: {
      pipeline: "Pipeline commercial",
      conversionSub: "Conversion",
      conversionRate: "Taux de conversion",
    },
    table: {
      name: "Nom",
      kind: "Type",
      status: "Statut",
      budget: "Budget",
      source: "Source",
      action: "",
    },
    statusLabels: {
      nouveau: "Nouveau",
      contacte: "Contacté",
      qualifie: "Qualifié",
      visite: "En visite",
      offre: "Offre",
      gagne: "Gagné",
      perdu: "Perdu",
    } as Record<string, string>,
    kindLabels: {
      acheteur: "Acheteur",
      vendeur: "Vendeur",
    } as Record<string, string>,
    typePersonneLabels: {
      particulier: "Particulier",
      professionnel: "Professionnel",
      societe: "Société",
      sci: "SCI",
      agence: "Agence",
    } as Record<string, string>,
    form: {
      title: "Lead",
      fullName: "Nom complet",
      email: "Email",
      phone: "Téléphone",
      source: "Source",
      kind: "Type",
      typePersonne: "Nature juridique",
      budgetMin: "Budget min (€)",
      budgetMax: "Budget max (€)",
      save: "Enregistrer",
      cancel: "Annuler",
    },
    detail: {
      backLink: "‹ Leads",
      eyebrowAcheteur: "Acquéreur",
      eyebrowVendeur: "Vendeur",
      eyebrowFallback: "Lead",
      fallbackName: "Lead sans nom",
      cardIdentite: "Identité & contact",
      cardBudget: "Budget",
      cardCriteres: "Critères de recherche",
      cardVisites: "Visites liées",
      cardBienLie: "Bien lié",
      cardEnrichissement: "Enrichissement",
      fields: {
        email: "Email",
        phone: "Téléphone",
        source: "Source",
        typePersonne: "Nature juridique",
        consentAt: "Consentement RGPD",
        enrichedAt: "Enrichi le",
        enrichedSource: "Source enrichissement",
        createdAt: "Créé le",
        updatedAt: "Dernière modif.",
        status: "Statut",
        notes: "Notes",
        title: "Titre",
      },
      budgetMin: "Budget min",
      budgetMax: "Budget max",
      criteres: {
        nom: "Nom du critère",
        typeBien: "Type de bien",
        surface: "Surface",
        pieces: "Pièces",
        budget: "Budget",
        zones: "Zones",
        dpeMax: "DPE max",
        terrasse: "Terrasse",
        parking: "Parking",
        ascenseur: "Ascenseur",
        jardin: "Jardin",
        piscine: "Piscine",
        actif: "Actif",
        oui: "Oui",
        non: "Non",
        surfaceRange: (min: number, max: number) => `${min} – ${max} m²`,
        piecesRange: (min: number, max: number) => `${min} – ${max} p.`,
      },
      emptyBudget: "Budget non renseigné.",
      emptyCriteres: "Aucun critère de recherche défini.",
      emptyVisites: "Aucune visite planifiée pour ce lead.",
      emptyBienLie: "Aucun bien lié.",
      emptyEnrichissement: "Aucune donnée d'enrichissement disponible.",
      enrich: {
        cardTitle: "Enrichissement B2B",
        intro: "Récupère les données professionnelles publiques de ce contact (entreprise, poste) via nos fournisseurs partenaires. Consentement requis.",
        button: "Enrichir ce contact",
        reenrich: "Réactualiser l'enrichissement",
        busy: "Enrichissement…",
        errorGeneric: "Enrichissement indisponible pour le moment.",
        errorNoEmail: "Un email est nécessaire pour enrichir ce contact.",
        errorNotConfigured: "Enrichissement non configuré (clés fournisseur absentes).",
        errorForbidden: "Enrichissement réservé aux contacts professionnels avec consentement.",
        errorRateLimited: "Trop de requêtes — réessayez dans un instant.",
        noData: "Aucune donnée trouvée pour ce contact.",
        empty: "Aucune donnée d'enrichissement pour l'instant.",
      },
      bienLie: {
        city: "Ville",
        price: "Prix affiché",
        type: "Type",
        seeProperty: "Voir la fiche bien ›",
      },
    },
  },
  visits: {
    eyebrow: "Visites",
    title: "Visites",
    sub: "Vos visites planifiées et passées.",
    newCta: "Planifier une visite",
    empty: "Aucune visite planifiée.",
    upcoming: "À venir",
    past: "Passées",
    delete: "Supprimer",
    cardTitle: "Visites",
    durationUnit: " min",
    kpis: {
      total: "Visites",
      upcoming: "À venir",
      done: "Réalisées",
      noShow: "No-show",
    },
    charts: {
      pipeline: "Pipeline",
      doneRate: "Taux de réalisation",
      doneRateSub: "Réalisées",
    },
    table: {
      property: "Bien",
      datetime: "Date",
      duration: "Durée",
      status: "Statut",
      action: "",
    },
    statusLabels: {
      planifiee: "Planifiée",
      confirmee: "Confirmée",
      realisee: "Réalisée",
      annulee: "Annulée",
      no_show: "No-show",
    } as Record<string, string>,
    form: {
      title: "Visite",
      property: "Bien",
      lead: "Lead",
      scheduledAt: "Date et heure",
      duration: "Durée (min)",
      notes: "Notes",
      save: "Enregistrer",
      cancel: "Annuler",
    },
  },
  prospection: {
    // ── Navigation & header
    title: "Prospection",
    kicker: "Veille marché",
    eyebrow: "Prospection",
    tabAcquereurs: "Acquéreurs",
    acquereurs: "Acquéreurs",
    annonces: "Annonces",
    matching: "Matching",
    criteres: "Critères",
    newAcquereurBtn: "+ Nouvel acquéreur",
    // ── KPI labels
    kpiAcquereurs: "Acquéreurs",
    kpiMatchs: "Matchs",
    kpiAnnonces: "Annonces",
    kpiAlertes: "Alertes",
    // ── Toolbar annonces
    eligibleOnly: "Mandats éligibles uniquement",
    refresh: "Rafraîchir",
    annonceCount: (n: number) => `${n} annonce${n > 1 ? "s" : ""}`,
    // ── Badges annonce
    badgePap: "Particulier",
    badgePro: "Pro",
    badgeBaissePrix: "Baisse de prix",
    badgeEligible: "Éligible mandat",
    badgeDpe: (note: string) => `DPE ${note}`,
    badgeAge: (h: number) => h < 24 ? `${h}h` : `${Math.floor(h / 24)}j`,
    // ── Carte annonce
    annonceVoir: "Voir l'annonce",
    annoncePrixM2: (v: number) => `${v.toLocaleString("fr-FR")} €/m²`,
    annonceSurface: (v: number) => `${v} m²`,
    annoncePieces: (v: number) => `${v} p.`,
    annoncePrix: (v: number) => `${Math.round(v / 1000)}k€`,
    annonceNoPhoto: "Aucune photo",
    annonceNoTitle: "Annonce sans titre",
    // ── Toolbar matching
    matchingHint: "Chaque annonce est confrontée aux critères de vos acquéreurs. Score, raisons et points bloquants sont détaillés pour décider vite.",
    matchGoodLabel: "Bon match",
    matchNextAction: "Prochaine action",
    matchContactBtn: "Contacter",
    contactSoon: "Action « Contacter » bientôt disponible.",
    // ── Empty states annonces
    emptyAnnonces: "Aucune annonce disponible.",
    emptyAnnoncesTitle: "Aucune annonce pour l'instant",
    emptyAnnoncesText: "Les annonces proviennent de vos recherches de prospection. Lancez une recherche pour importer les biens d'une zone et les confronter à vos acquéreurs.",
    emptyAnnoncesStep1: "Cliquer sur « Lancer une prospection »",
    emptyAnnoncesStep2: "Renseigner une zone (ville ou code postal) et vos critères",
    emptyAnnoncesStep3: "Les annonces trouvées s'affichent ici, prêtes à être qualifiées",
    // ── Empty states matchs
    emptyMatchs: "Aucun match. Créez des critères acquéreur dans l'onglet Critères.",
    emptyMatchsTitle: "Aucun match calculé",
    emptyMatchsText: "Le moteur de matching compare chaque annonce aux critères de vos acquéreurs. Pour démarrer, créez au moins un profil acquéreur.",
    emptyMatchsStep1: "Aller dans l'onglet « Critères »",
    emptyMatchsStep2: "Créer un profil acquéreur avec budget, zones et surface",
    emptyMatchsStep3: "Le moteur calcule les matchs lors de la prochaine ingestion",
    // ── Empty states critères / acquéreurs
    emptyCriteres: "Aucun critère. Créez un profil acquéreur pour démarrer le matching.",
    emptyCriteresTitle: "Aucun acquéreur configuré",
    emptyCriteresText: "Ajoutez vos acquéreurs avec leurs critères de recherche. Le moteur leur envoie une alerte à chaque nouvelle annonce correspondante.",
    emptyCriteresStep1: "Cliquer sur « + Nouveau critère »",
    emptyCriteresStep2: "Renseigner les zones, le budget et la surface souhaitée",
    emptyCriteresStep3: "Activer les alertes email ou WhatsApp",
    // ── Degraded
    degradedAnnonces: "Module prospection indisponible : schéma ou migration manquante.",
    // ── Critères form
    criteresCount: (count: number) => `${count} critère${count > 1 ? "s" : ""} actif${count > 1 ? "s" : ""}`,
    newCritere: "+ Nouveau critère",
    critereNamePlaceholder: "Nom du critère (ex: Famille Martin)",
    critereZonesPlaceholder: "Zones (codes postaux séparés par virgule : 75011,75012)",
    budgetMaxPlaceholder: "Budget max (€)",
    surfaceMinPlaceholder: "Surface min (m²)",
    save: "Enregistrer",
    saving: "Enregistrement…",
    delete: "Supprimer",
    // ── Errors
    feedbackError: "Impossible d'enregistrer le feedback.",
    saveError: "Impossible d'enregistrer le critère.",
    deleteError: "Impossible de supprimer le critère.",
    loadAnnoncesError: "Impossible de charger les annonces.",
    loadMatchsError: "Impossible de charger les matchs.",
    loadCriteresError: "Impossible de charger les critères.",
    critereNameRequired: "Nom du critère requis.",
    // ── Accessibility labels
    emptyStepsAria: "Étapes pour démarrer",
    feedbackDislikeAria: "Je n'aime pas",
    feedbackLikeAria: "J'aime",
    // ── Spinner
    loading: "Chargement…",
    // ── Acquereurs table headers
    colNom: "Nom",
    colBudget: "Budget",
    colZones: "Zones",
    colContact: "Contact",
    colCriteres: "Critères",
    colAction: "Action",
    // ── Scrape personnalisé (Lot 2)
    scrapeBtn: "Lancer une prospection",
    scrapeModalTitle: "Prospection personnalisée",
    scrapeIntro: "Recherche des annonces selon vos critères, puis les confronte à vos acquéreurs actifs.",
    scrapeVille: "Ville ou code postal",
    scrapeVillePlaceholder: "Antibes, Cannes, 06600…",
    scrapeType: "Type de bien",
    scrapeTypeAppart: "Appartement",
    scrapeTypeMaison: "Maison",
    scrapeBudgetMin: "Budget min (€)",
    scrapeBudgetMax: "Budget max (€)",
    scrapeSurfaceMin: "Surface min (m²)",
    scrapeSurfaceMax: "Surface max (m²)",
    scrapePiecesMin: "Pièces min",
    scrapeMotsCles: "Mots-clés (séparés par virgule)",
    scrapeMotsClesPlaceholder: "terrasse, vue mer, sud…",
    scrapeSubmit: "Rechercher",
    scrapeSubmitting: "Recherche en cours…",
    scrapeCancel: "Fermer",
    scrapeVilleRequired: "Ville ou code postal requis.",
    scrapeNoProvider: "Aucun fournisseur d'annonces configuré. Ajoutez une clé Apify pour lancer une recherche.",
    scrapeError: "La recherche a échoué. Réessayez.",
    scrapeResultTitle: "Résultats de la recherche",
    scrapeResultSummary: (scraped: number, kept: number, inserted: number) =>
      `${scraped} annonce${scraped > 1 ? "s" : ""} trouvée${scraped > 1 ? "s" : ""} · ${kept} retenue${kept > 1 ? "s" : ""} · ${inserted} nouvelle${inserted > 1 ? "s" : ""}`,
    scrapeResultMatched: (n: number) => `${n} match${n > 1 ? "s" : ""} avec vos acquéreurs`,
    scrapeResultEmpty: "Aucune annonce ne correspond à ces critères pour le moment. Élargissez la recherche ou réessayez plus tard.",
    scrapeTopMatchsTitle: "Meilleurs matchs",
    scrapeMatchLine: (nom: string, score: number) => `${nom} — score ${score}/100`,
    scrapeSeeAnnonces: "Voir les annonces",
    scrapeSeeMatchs: "Voir les matchs",
    // ── Criteres table headers
    colBudgetMax: "Budget Max",
    // ── Annonces table headers (legacy fallback)
    colAnnonce: "Annonce",
    colPrix: "Prix",
    colTags: "Tags",
    // ── Matching table headers
    colScore: "Score",
    colActions: "Actions",
    // ── Recommandation (dérivée du score, seuils partagés RECOMMENDATION_THRESHOLDS)
    recoHighPriority: "Priorité haute",
    recoReview: "À revoir",
    recoLowPriority: "Priorité basse",
    recoRejected: "Écarté",
    recoTitleAria: "Niveau de priorité du match",
    // ── Explicabilité match
    reasonsWhy: "Pourquoi ce match",
    reasonsSatisfied: "Critères satisfaits",
    reasonsBlocking: "Points bloquants",
    reasonsMissing: "Données manquantes",
    reasonsFactor: (label: string, pts: number) =>
      `${label} : ${pts > 0 ? "+" : ""}${pts}`,
    reasonsScoreCapped: "Score plafonné (données essentielles manquantes)",
    reasonsNone: "Aucun facteur détaillé disponible.",
    scoreOutOf: (score: number) => `${score}/100`,
    // ── Détail annonce
    detailOpen: "Voir le détail",
    detailTitle: "Détail de l'annonce",
    detailSectionData: "Données de l'annonce",
    detailSectionCrm: "Rattachement CRM",
    detailSectionActions: "Actions",
    detailProvider: "Source provider",
    detailProviderTag: "Provider",
    detailConfirmedTag: "Confirmé (CRM)",
    detailFieldType: "Type de bien",
    detailFieldPrix: "Prix affiché",
    detailFieldPrixM2: "Prix au m²",
    detailFieldSurface: "Surface",
    detailFieldPieces: "Pièces",
    detailFieldVille: "Commune",
    detailFieldCp: "Code postal",
    detailFieldDpe: "DPE",
    detailFieldNc: "Non communiqué",
    detailScore: "Score de matching",
    detailNoScore: "Annonce non matchée à un acquéreur.",
    // ── Comparaison estimation (valuation)
    valuationTitle: "Comparaison avec l'estimation",
    valuationBelow: "Sous la fourchette (opportunité)",
    valuationWithin: "Dans la fourchette",
    valuationAbove: "Au-dessus de la fourchette (surcoté)",
    valuationLowConfidence: "Estimation peu fiable",
    valuationUnavailable: "Estimation indisponible",
    valuationPending: "Estimation en cours de calcul…",
    valuationMarketValue: (v: number) => `Valeur estimée : ${v.toLocaleString("fr-FR")} €`,
    valuationDelta: (eur: number, pct: number) =>
      `Écart : ${eur > 0 ? "+" : ""}${eur.toLocaleString("fr-FR")} € (${pct > 0 ? "+" : ""}${pct} %)`,
    // ── CRM lié
    crmLeadLinked: "Lead vendeur rattaché",
    crmPropertyLinked: "Bien rattaché",
    crmEstimationLinked: "Estimation rattachée",
    crmNothingLinked: "Aucun rattachement CRM pour le moment.",
    // ── Liens de continuité vers les fiches créées (routes vérifiées existantes)
    crmOpenLead: "Ouvrir la fiche client",
    crmOpenProperty: "Ouvrir la fiche bien",
    crmOpenEstimation: "Ouvrir l'estimation",
    // ── Actions annonce
    actionLinkCrm: "Créer lead + bien",
    actionLinkCrmDoing: "Création…",
    actionLinkCrmDone: "Lead et bien créés dans le CRM.",
    actionEstimate: "Estimer ce bien",
    actionEstimateDoing: "Estimation…",
    actionEstimateDone: "Estimation créée (brouillon).",
    actionContact: "Préparer un contact",
    actionContactDoing: "Préparation…",
    actionContactDone: "Brouillon de contact généré.",
    actionContactDraftNotSent: "Brouillon — non envoyé (à confirmer ou provider absent).",
    actionOptout: "Ne pas démarcher",
    actionOptoutDoing: "Enregistrement…",
    actionOptoutDone: "Marqué en opt-out — ne plus démarcher.",
    actionOptoutConfirm: "Marquer cette annonce comme « ne pas démarcher » ?",
    actionCanal: "Canal de contact",
    actionCanalEmail: "Email",
    actionCanalSms: "SMS",
    actionCanalWhatsapp: "WhatsApp",
    actionContactTemplate: (titre: string) =>
      `Bonjour, je me permets de vous contacter au sujet de votre annonce « ${titre} ». Seriez-vous ouvert à une estimation gratuite de votre bien ?`,
    actionError: "L'action a échoué. Réessayez.",
    detailClose: "Fermer",
    // ── KPI supplémentaire
    kpiHighPriority: "Priorité haute",

    // ═══ REA-PLATFORM-002 (A1) — cockpit de demande immobilière ═══
    // ── Onglets ajoutés
    tabProfils: "Profils de recherche",
    tabHistorique: "Historique",
    tabAlertes: "Alertes",
    // ── Acquéreurs regroupés (multi-profil)
    acquereurProfilsTitle: "Profils de recherche par acquéreur",
    acquereurProfilsHint: "Un acquéreur peut avoir plusieurs profils de recherche. Chaque profil est confronté au marché indépendamment.",
    acquereurProfilCount: (n: number) => `${n} profil${n > 1 ? "s" : ""} de recherche`,
    acquereurNoLead: "Profils non rattachés à un acquéreur",
    acquereurOpenLead: "Ouvrir la fiche acquéreur",
    profilEssentiels: "Critères essentiels",
    profilSecondaires: "Souhaits secondaires",
    profilExclusions: "Exclusions",
    profilNoSecondaire: "Aucun souhait secondaire.",
    profilNoExclusion: "Aucune exclusion.",
    profilEdit: "Modifier",
    profilBudget: "Budget",
    profilSurface: "Surface",
    profilPieces: "Pièces",
    profilTypes: "Types de bien",
    profilAlerte: "Alerte",
    // ── Urgence acquéreur
    urgenceLabel: "Urgence",
    urgenceFaible: "Faible",
    urgenceNormale: "Normale",
    urgenceHaute: "Haute",
    urgenceUrgente: "Urgente",
    urgenceNone: "Non précisée",
    // ── Formulaire critère enrichi (0043)
    formSectionEssentiels: "Critères essentiels (bloquants)",
    formSectionSecondaires: "Souhaits secondaires (non bloquants)",
    formSectionExclusions: "Exclusions (rejets)",
    formSectionAlerte: "Préférences d'alerte",
    formUrgence: "Urgence de l'acquéreur",
    formBudgetMin: "Budget min (€)",
    formPiecesMin: "Pièces min",
    formExclusionsPlaceholder: "Rejets séparés par virgule : rez-de-chaussée, travaux, vis-à-vis",
    formExclusionsHint: "Non bloquant côté moteur : signale les biens à écarter à la lecture.",
    formSecondairesPlaceholder: "Souhaits séparés par virgule : vue mer, calme, exposition sud",
    formSecondairesHint: "Préférences confort, pondérées plus bas que les critères essentiels.",
    formAlerteFrequence: "Fréquence d'alerte",
    freqImmediate: "Immédiate",
    freqQuotidien: "Quotidienne",
    freqHebdo: "Hebdomadaire",
    freqOff: "Désactivée",
    critereUpdated: "Profil mis à jour.",
    updateError: "Impossible de mettre à jour le profil.",
    // ── Matching : explication structurée
    matchSatisfied: "Critères satisfaits",
    matchImperfect: "Critères imparfaits",
    matchBlocking: "Éléments bloquants",
    matchMissingData: "Données manquantes",
    matchNextRecommended: "Prochaine action recommandée",
    matchFactorPts: (label: string, pts: number) => `${label} · ${pts > 0 ? "+" : ""}${pts} pts`,
    matchNextContact: "Préparer un contact vendeur",
    matchNextReview: "À revoir avant proposition",
    matchNextPropose: "Proposer à l'acquéreur",
    matchNextLowPriority: "Priorité basse — traiter après les autres",
    matchExplainNone: "Aucun facteur détaillé sur ce match.",
    // ── Historique des propositions (LIVE)
    historyTitle: "Historique des propositions",
    historyHint: "Ce qui a été proposé, retenu ou refusé pour chaque acquéreur — signaux réels enregistrés.",
    historyEmpty: "Aucune proposition enregistrée pour l'instant.",
    historyEmptyHint: "Les pouces 👍 / 👎 sur les matchs et les tentatives de contact alimentent cet historique.",
    historyRetenue: "Retenue",
    historyRefusee: "Refusée",
    historyContactee: "Contactée",
    historyVisitee: "Visitée",
    historyContactAttempts: "Tentatives de contact",
    historyContactDraft: "Brouillon (non envoyé)",
    historyContactApproved: "Approuvé",
    historyContactSent: "Envoyé",
    historyContactFailed: "Échec",
    historyContactOptedOut: "Opt-out",
    historyContactReplied: "Réponse reçue",
    historyCountRetenues: (n: number) => `${n} retenue${n > 1 ? "s" : ""}`,
    historyCountRefusees: (n: number) => `${n} refusée${n > 1 ? "s" : ""}`,
    historyScore: (s: number) => `score ${s}/100`,
    historyLoadError: "Impossible de charger l'historique.",
    // ── Préférences d'alertes (CONFIG LIVE + APERÇU envoi)
    alertsTitle: "Préférences d'alertes",
    alertsHint: "Réglez la fréquence de veille par profil de recherche. La configuration est enregistrée ; l'envoi réel n'est pas branché.",
    alertsPreviewBadge: "Aperçu — envoi non branché",
    alertsPreviewExplain: "Aucun email ni WhatsApp n'est envoyé depuis cet écran. Vous configurez ici la fréquence souhaitée et visualisez les garde-fous qui s'appliqueront quand un canal sera raccordé.",
    alertsFrequencyFor: (nom: string) => `Fréquence pour « ${nom} »`,
    alertsGuardrailsTitle: "Garde-fous d'envoi (à l'activation)",
    alertsGuardHumanConfirm: "Validation humaine obligatoire avant tout envoi",
    alertsGuardCooldown: (h: number) => `Cooldown ${h} h par annonce (anti-doublon)`,
    alertsGuardCap: (n: number) => `Plafond ${n} envois WhatsApp / jour / agence`,
    alertsGuardOptOut: "Désinscription (opt-out) respectée avant contact",
    alertsSaved: "Fréquence enregistrée.",
    alertsSaveError: "Impossible d'enregistrer la fréquence.",
    alertsChannelEmail: "Email",
    alertsChannelWhatsapp: "WhatsApp",
    alertsChannelHint: "Canaux prévus, non raccordés",
  },
  mandates: {
    eyebrow: "Juridique",
    title: "Mandats",
    sub: "Vos mandats de vente — simple, exclusif, semi-exclusif.",
    newCta: "Nouveau mandat",
    empty: "Aucun mandat. Signez votre premier mandat.",
    delete: "Supprimer",
    cardTitle: "Mandat",
    noReference: "Sans référence",
    commissionUnit: " %",
    kpis: {
      total: "Mandats",
      active: "Actifs",
      underMandate: "Valeur sous mandat",
      avgCommission: "Commission moy.",
    },
    charts: {
      pipeline: "Pipeline",
      byKind: "Par type de mandat",
    },
    table: {
      reference: "Référence",
      price: "Prix",
      commission: "Commission",
      status: "Statut",
      kind: "Type",
      expires: "Expire",
      action: "",
    },
    statusLabels: {
      brouillon: "Brouillon",
      actif: "Actif",
      suspendu: "Suspendu",
      expire: "Expiré",
      resilie: "Résilié",
      realise: "Réalisé",
    } as Record<string, string>,
    kindLabels: {
      simple: "Simple",
      exclusif: "Exclusif",
      semi_exclusif: "Semi-exclusif",
    } as Record<string, string>,
    form: {
      title: "Mandat",
      property: "Bien",
      reference: "Référence",
      kind: "Type",
      askingPrice: "Prix affiché (€)",
      commissionPct: "Commission (%)",
      signedAt: "Signé le",
      expiresAt: "Expire le",
      save: "Enregistrer",
      cancel: "Annuler",
    },
    detail: {
      kicker: "Mandat",
      fallbackTitle: "Mandat sans titre",
      backLink: "‹ Mandats",
      cardMandat: "Détail du mandat",
      cardBien: "Bien lié",
      cardVisites: "Visites du bien",
      fields: {
        kind: "Type de mandat",
        reference: "Référence",
        askingPrice: "Prix affiché",
        commissionPct: "Commission",
        commissionAmount: "Montant commission",
        signedAt: "Signé le",
        expiresAt: "Expire le",
        daysLeft: (d: number) => `${d} jour${d !== 1 ? "s" : ""} restant${d !== 1 ? "s" : ""}`,
        daysExpired: "Expiré",
        notes: "Notes",
        updatedAt: "Dernière modif.",
      },
      expiringWarning: "Expire bientôt",
      wellLinked: "Voir la fiche bien",
      wellType: "Type",
      wellCity: "Ville",
      wellSurface: "Surface",
      wellPrice: "Prix affiché",
      wellStatus: "Statut",
      visitDate: "Date",
      visitContact: "Contact",
      emptyVisits: "Aucune visite planifiée pour ce bien.",
      emptyWell: "Aucun bien lié à ce mandat.",
    },
  },
  agenda: {
    eyebrow: "Agenda",
    title: "Agenda",
    sub: "Vue d'ensemble de vos visites à venir.",
    kpis: {
      thisWeek: "Cette semaine",
      today: "Aujourd'hui",
      toConfirm: "À confirmer",
    },
    locationSeparator: " — ",
    noProperty: "Bien non renseigné",
    noContact: "Contact non renseigné",
    openProperty: "Voir le bien",
    openContact: "Voir le contact",
  },
  profile: {
    eyebrow: "Compte",
    title: "Profil",
    sub: "Session active. Identité et périmètre d'accès.",
    identityTitle: "Identité",
    scopesTitle: "Scopes",
    sessionTitle: "Session",
    sessionHint: "Fermer la session sur cet appareil.",
    integrationsTitle: "Intégrations",
    aigentLink: "Consulter et lancer les agents publiés, suivre leurs exécutions et valider les interruptions.",
    mfa: {
      title: "Double authentification (2FA)",
      titleEnabled: "Double authentification (2FA) — activée",
      badge: "2FA activée",
      step1: "Étape 1 —",
      step2: "Étape 2 —",
      secretLabel: "Clé secrète",
      uriLabel: "URI otpauth (copier dans une app)",
      codeLabel: "Code de vérification",
      codePlaceholderDisable: "123456 ou code de secours",
      backupWarning: "⚠ Codes de secours — notez-les maintenant.",
    },
    integrationsHint: "Connectez vos services Google pour que l'assistant puisse les utiliser. Ce panneau ne fait que rendre visible et gérer les connexions existantes.",
    integrations: {
      loadError: "Impossible de récupérer l'état des intégrations. Réessayez.",
      notConfigured: "Intégrations indisponibles : la clé API Composio est absente côté serveur.",
      connected: "Connecté",
      disconnected: "Non connecté",
      notConfiguredBadge: "Non configuré",
      connect: "Connecter",
      connecting: "Connexion…",
      missingProviderConfig: "Configuration absente côté serveur pour ce service.",
      connectError: "Connexion impossible. Réessayez.",
      capabilitiesLabel: "Ce que ça permet",
      testInChat: "Testez-le dans le chat (« scanne mes emails »).",
      providers: {
        gmail: {
          name: "Gmail",
          description: "Lecture limitée de vos emails pour détecter les demandes d'estimation.",
          capabilities: [
            "Détecter les demandes d'estimation reçues par email",
            "Pré-remplir un brouillon d'estimation après votre confirmation",
          ],
        },
        calendar: {
          name: "Google Calendar",
          description: "Permettra à l'assistant de lire vos rendez-vous et vos disponibilités.",
          capabilities: [
            "Lire vos événements à venir",
            "Répondre à vos questions d'agenda dans le chat",
          ],
        },
      },
    },
    fields: {
      email: "Email",
      userId: "User ID",
      tenant: "Tenant",
      role: "Rôle",
      issued: "Session émise",
    },
    empty: "—",
  },
  /**
   * Frontière consommateur Aigent — libellé de section (renvoi Profil → /agents).
   * Le panneau verbeux a été retiré : la page /agents (UI.agentsPage) est la
   * surface unique d'exploitation. On ne garde ici que le titre de section.
   */
  aigent: {
    sectionTitle: "Copilotes IA (Aigent)",
  },
  agentsPage: {
    // En-tête
    kicker: "Aigent",
    title: "Agents",
    metaConnected: "Registre raccordé",
    metaUnavailable: "Registre non connecté",
    kpiPublished: "Publiés",
    kpiRunnable: "Exécutables",
    kpiWaiting: "En attente",
    refresh: "Actualiser",
    refreshing: "Actualisation…",
    // États de raccordement (honnêtes)
    statusLive: "Connecté",
    statusUnavailable: "Non connecté",
    // Registre vide
    emptyTitle: "Aucun agent déployé pour ce projet",
    emptyBody:
      "Les agents métier sont conçus, testés et publiés depuis Aigent. Dès qu'un agent est déployé pour ce projet, il apparaît ici — prêt à être lancé et suivi.",
    // Indisponible (vars absentes / injoignable)
    unavailableTitle: "Aigent non connecté",
    unavailableReasons: {
      not_configured:
        "Aucune configuration Aigent détectée sur ce serveur : les variables AIGENT_RUNTIME_BASE_URL et AIGENT_RUNTIME_TOKEN sont absentes. Renseignez-les côté serveur (jamais dans le navigateur) — les agents publiés apparaîtront ici dès que la liaison sera établie.",
      unreachable:
        "Aigent ne répond pas pour le moment. Aucune donnée n'est chargée tant que la liaison n'est pas rétablie.",
      unauthorized:
        "L'accès au registre Aigent a été refusé. Aucune donnée n'est chargée tant que l'accès n'est pas rétabli.",
      not_provisioned:
        "Le registre Aigent est configuré mais pas encore branché pour ce projet. Rien n'est exécuté tant que la liaison n'est pas active.",
      error: "Aigent injoignable pour le moment. Aucune donnée n'est inventée.",
    } as Record<string, string>,
    // Chargement / erreur
    loadError: "Impossible de charger les agents.",
    retry: "Réessayer",
    // Statuts de version d'agent (contrat §5)
    agentStatus: {
      specification: "Spécification",
      draft: "Brouillon",
      testing: "En test",
      production: "En production",
      paused: "En pause",
      unavailable: "Indisponible",
    } as Record<string, string>,
    versionLabel: "Version",
    capabilitiesLabel: "Capacités",
    hitlBadge: "Validation humaine",
    // Lancement
    launch: "Lancer",
    launching: "Lancement…",
    launchDisabledHint: "Lancement indisponible tant qu'aucun agent n'est déployé.",
    launchBlockedStatus: "Cet agent n'est pas exécutable dans son état actuel.",
    runStarted: "Run lancé",
    runStartFailed: "Le lancement a échoué.",
    // Suivi de run
    runsTitle: "Exécutions",
    runsEmpty: "Aucune exécution pour le moment.",
    close: "Fermer",
    runStatus: {
      queued: "En file",
      running: "En cours",
      waiting_on_input: "Attente de validation",
      completed: "Terminé",
      failed: "Échec",
      cancelled: "Annulé",
    } as Record<string, string>,
    eventsTitle: "Événements",
    eventsEmpty: "Aucun événement.",
    resultTitle: "Résultat",
    provenanceLabel: "Provenance",
    sourcesLabel: "Sources",
    noSources: "Aucune source citée.",
    // HITL (approuver / modifier / refuser)
    hitlTitle: "Validation requise",
    hitlBody: "Cette exécution attend votre décision avant de poursuivre.",
    approve: "Approuver",
    reject: "Refuser",
    deciding: "Envoi…",
    decisionSent: "Décision transmise",
    decisionFailed: "La décision n'a pas pu être transmise.",
    notWaiting: "Cette exécution n'attend plus de décision.",
    // Historique
    historyTitle: "Historique",
    // Frontières (ce que la page ne fait pas)
    boundaryTitle: "Cockpit d'exploitation",
    boundaryBody:
      "Cette page pilote des agents déjà publiés — les consulter, les lancer, suivre leurs exécutions et valider les interruptions. La conception, le prompt, le graphe, le déploiement et la promotion des agents vivent exclusivement dans Aigent.",
  },
  login: {
    eyebrow: "Connexion",
    title: APP_NAME,
    sub: "Identifiants requis pour accéder au dashboard.",
    emailLabel: "Email",
    passwordLabel: "Mot de passe",
    submit: "Se connecter",
    submitBusy: "Connexion…",
    errors: {
      invalid_credentials: "Email ou mot de passe incorrect.",
      invalid_body: "Formulaire invalide.",
      database_not_configured: "Backend indisponible. Réessaie dans 1 min.",
      jwt_not_configured: "Backend mal configuré (JWT).",
      rate_limited: "Trop de tentatives. Réessaie dans 1 min.",
      generic: "Erreur de connexion.",
      network: "Erreur réseau.",
    } as Record<string, string>,
  },
  chat: {
    status: "Assistant IA",
    title: "Assistant",
    collapse: "Replier",
    reopen: "Chat",
    placeholder: "Message à l'assistant…",
    empty: "Pose une question, ou « mémorise : … » pour enregistrer un fait du tenant.",
    userAvatar: "VO",
    assistantAvatar: "IA",
    errorPrefix: "Erreur",
  },
  /**
   * Visite guidée du produit (REA-ONBOARDING-011).
   * ---------------------------------------------------------------
   * `chrome`  = textes du moteur (boutons, statut, repli cible absente).
   * `tours.*` = textes métier d'UNE visite. Chaque worker de tour ajoute SA
   *             clé sous `tours` (prospection, crm, estimations, offmarket,
   *             communications-hitl, agents, radar) sur ce modèle :
   *             { title, description, steps: { <stepId>: { title, body, consequence? } } }
   * Règle : jamais « Cliquez ici pour continuer », jamais de faux statut LIVE.
   */
  onboarding: {
    chrome: {
      dialogLabel: "Visite guidée",
      stepLabel: (current: number, total: number) => `Étape ${current} sur ${total}`,
      next: "Suivant",
      prev: "Précédent",
      finish: "Terminer",
      skip: "Passer la visite",
      close: "Fermer la visite",
      /** Affiché quand l'élément pointé n'existe pas sur l'écran courant. */
      targetMissing: "Cet élément n'est pas affiché sur cet écran. L'explication reste valable.",
      /** Rappel permanent : la visite ne fait rien à la place de l'utilisateur. */
      readOnly: "La visite montre et explique. Elle n'exécute aucune action à ta place.",
      loading: "Recherche de l'élément…",
    },
    /**
     * Écran d'accueil du PREMIER accès authentifié (W6, LOT 4).
     * Introduction courte, jamais bloquante : « Plus tard » referme sans rien
     * marquer comme fait, et une visite quittée reprend à sa dernière étape.
     */
    welcome: {
      title: "Bienvenue dans votre cockpit immobilier",
      promise:
        "Identifiez les opportunités, priorisez vos actions et gardez le contrôle sur chaque automatisation.",
      note: "La visite montre et explique. Tu peux l'arrêter à tout moment : elle reprendra où tu l'as laissée.",
      start: "Commencer la visite",
      later: "Plus tard",
      dialogLabel: "Bienvenue",
    },
    /**
     * Checklist de démarrage (W6, LOT 6). La complétion est DÉRIVÉE des données
     * réelles du compte — jamais d'une case cochée à la main. Trois états :
     * fait / à faire / indéterminé (table absente sur cet environnement).
     */
    checklist: {
      title: "Prise en main",
      description: "Sept repères pour rendre le cockpit utile sur ton activité.",
      progress: (done: number, total: number) => `${done} sur ${total}`,
      open: "Ouvrir la prise en main",
      collapse: "Réduire la prise en main",
      hide: "Masquer",
      done: "Fait",
      todo: "À faire",
      unknown: "Indéterminé",
      /** État honnête : la donnée n'est pas lisible ici, donc on ne conclut pas. */
      unknownHint:
        "Cette donnée n'est pas disponible sur cet environnement : impossible de dire si c'est fait.",
      completedTitle: "Prise en main terminée",
      completedBody: "Tu retrouves cette liste quand tu veux depuis l'aide.",
      items: {
        "first-lead": {
          label: "Créer un premier client",
          hint: "Un contact acheteur ou vendeur dans le CRM.",
        },
        "first-property": {
          label: "Ajouter un premier bien",
          hint: "Un bien de ton portefeuille, même incomplet.",
        },
        "first-estimation": {
          label: "Créer une estimation",
          hint: "Un avis de valeur à partir d'une adresse.",
        },
        "buyer-criteria": {
          label: "Définir un critère acquéreur",
          hint: "Budget, secteur, surface : la base du matching.",
        },
        "first-match": {
          label: "Consulter un matching",
          hint: "Les annonces qui correspondent à un critère.",
        },
        "first-draft": {
          label: "Préparer un brouillon",
          hint: "Un message prêt à relire avant tout envoi.",
        },
        "action-center": {
          label: "Consulter le Centre d'actions",
          hint: "Tes priorités du jour, sur le tableau de bord.",
        },
      } as Record<string, { label: string; hint: string }>,
    },
    /**
     * Panneau « Aide et visites guidées » (W6, LOT 7). Chaque visite est
     * relançable manuellement, même terminée.
     */
    help: {
      entry: "Aide et visites guidées",
      title: "Aide et visites guidées",
      description: "Chaque visite pointe des composants réels et explique quoi en faire.",
      close: "Fermer l'aide",
      start: "Commencer",
      resume: "Reprendre",
      replay: "Rejouer",
      unavailable: "Bientôt disponible",
      resetting: "Réinitialisation…",
      /** Libellés des visites listées dans le panneau, dans l'ordre d'apprentissage. */
      entries: {
        "core-cockpit": "Découvrir le cockpit",
        prospection: "Prospection et matching",
        crm: "Clients et portefeuille",
        estimations: "Estimations",
        offmarket: "Off-market",
        "communications-hitl": "Communications et approbations",
        agents: "Agents",
      } as Record<string, string>,
      status: {
        idle: "Jamais lancée",
        running: "En cours",
        completed: "Terminée",
        skipped: "Interrompue",
      } as Record<string, string>,
      /** Action secondaire discrète posée sur les pages prioritaires. */
      pageTour: "Découvrir cette page",
    },
    tours: {
      "core-cockpit": {
        title: "Prendre en main le cockpit",
        description:
          "Les repères de base : navigation, priorités du jour, assistant et compte.",
        steps: {
          welcome: {
            title: "Bienvenue dans le cockpit",
            body: "En quelques étapes, tu vois où se trouvent la navigation, tes priorités du jour et l'assistant.",
            consequence: "Rien n'est modifié pendant la visite : tu peux l'arrêter à tout moment avec Échap.",
          },
          nav: {
            title: "La navigation",
            body: "Le rail de gauche regroupe tous les modules : CRM, estimations, prospection, off-market, agents.",
          },
          actionCenter: {
            title: "Tes priorités du jour",
            body: "Le centre d'actions classe ce qui mérite ton attention : relances en retard, mandats à renouveler, visites à débriefer.",
          },
          assistant: {
            title: "L'assistant",
            body: "Le panneau de droite répond en langage naturel et sait lire tes données : « quels leads sans relance depuis 15 jours ? ».",
            consequence: "Il demande confirmation avant toute action irréversible, comme la suppression d'un lead.",
          },
          profile: {
            title: "Ton compte",
            body: "Le profil regroupe tes informations et la déconnexion.",
          },
          wrapup: {
            title: "Tu as les repères",
            body: "Chaque module a sa propre visite, lançable quand tu en as besoin.",
          },
          dashboardNewEstimation: {
            title: "Démarrer une estimation",
            body: "L'action principale de l'accueil ouvre l'entretien d'estimation : adresse, surface, état du bien, puis la valeur argumentée.",
            consequence: "Le bouton ouvre l'entretien. Rien n'est enregistré tant que tu ne l'as pas lancé toi-même.",
          },
          dashboardKpis: {
            title: "Tes quatre chiffres",
            body: "Biens au portefeuille, clients actifs, visites à venir et mandats en cours. Recalculés à chaque chargement, sur tes seules données.",
          },
          dashboardActionCenter: {
            title: "Le bloc des priorités",
            body: "Chaque ligne est rattachée à une vraie fiche et dit pourquoi elle remonte : relance en retard, rendez-vous du jour, estimation à reprendre.",
            consequence: "« Traité » et « Reporter » modifient la tâche. La visite te les montre, elle ne les déclenche pas.",
          },
          dashboardRecentProperties: {
            title: "Ton portefeuille récent",
            body: "Les derniers biens modifiés, avec statut, type et ville. Une ligne ouvre la fiche complète du bien.",
          },
        },
      },

      /* ── W4 — prospection / radar / off-market ─────────────────────── */

      prospection: {
        title: "Faire tourner la prospection",
        description:
          "Des critères acquéreur aux annonces rapprochées, avec le score réel et ses raisons.",
        steps: {
          onglets: {
            title: "Les cinq onglets",
            body: "Acquéreurs, matching, annonces, historique et alertes : chaque onglet est une étape du flux de prospection.",
          },
          criteres: {
            title: "Les critères acquéreur",
            body: "Un profil décrit ce que cherche un acquéreur : secteur, budget, surface, pièces. C'est la base de tout rapprochement.",
            consequence:
              "La visite ne modifie aucun critère : le formulaire refuse d'enregistrer tant qu'elle est ouverte.",
          },
          annonces: {
            title: "Les annonces collectées",
            body: "L'onglet Annonces liste les biens remontés par la collecte : prix, prix au m², DPE, ancienneté et vendeur particulier ou professionnel.",
          },
          matching: {
            title: "Le matching et son score",
            body: "Chaque rapprochement affiche un score calculé par le moteur de prospection, jamais estimé à l'œil. Sous chaque ligne, les critères satisfaits, tolérés et bloquants expliquent le chiffre.",
            consequence:
              "Score et raisons viennent de tes données réelles ; la visite ne relance aucun calcul.",
          },
          feedback: {
            title: "Ton retour et les alertes",
            body: "Les pouces sur chaque rapprochement apprennent tes préférences et repondèrent les critères suivants. L'onglet Alertes prévient au-delà d'un score que tu choisis.",
            consequence:
              "Pendant la visite, les pouces n'enregistrent rien : aucun signal n'est envoyé au moteur.",
          },
        },
      },

      radar: {
        title: "Lire le radar vendeurs",
        description:
          "Les trois signaux d'opportunité et comment ouvrir l'annonce ou le mandat derrière chacun.",
        steps: {
          baisses: {
            title: "Les baisses de prix",
            body: "Chaque ligne compare l'ancien et le nouveau prix d'une annonce suivie, avec l'écart en euros, en pourcentage et la date du relevé.",
            consequence:
              "« Voir l'annonce » ouvre l'annonce d'origine dans un nouvel onglet, pour vérifier avant d'appeler.",
          },
          dormantes: {
            title: "Les annonces dormantes",
            body: "Un bien en ligne depuis longtemps sans mise à jour signale souvent un vendeur prêt à discuter d'un nouveau mandat.",
            consequence:
              "« Voir l'annonce » ouvre l'annonce d'origine pour confirmer qu'elle est toujours active.",
          },
          mandats: {
            title: "Les mandats qui expirent",
            body: "Tes propres mandats classés par jours restants. Passée l'échéance, le bien redevient disponible pour un confrère.",
            consequence:
              "« Ouvrir » t'emmène sur la liste des mandats, d'où tu lances le renouvellement.",
          },
        },
      },

      offmarket: {
        title: "Rapprocher un bien de tes acquéreurs",
        description:
          "Du bien du portefeuille au lien partageable, en comprenant chaque score.",
        steps: {
          bien: {
            title: "Choisis un bien réel",
            body: "La colonne de gauche liste les biens de ton portefeuille. Cliquer sur un bien interroge le moteur de matching pour trouver les acquéreurs de ta base qui lui correspondent.",
          },
          inclure: {
            title: "Coche les biens à inclure",
            body: "La case devant chaque bien décide de ce qui figurera dans la sélection envoyée à l'acquéreur. Tu peux en cocher plusieurs.",
          },
          acquereurs: {
            title: "Les acquéreurs correspondants",
            body: "Chaque ligne est un profil de recherche de ta base, avec sa recommandation : priorité haute, à revoir, priorité basse ou rejeté.",
          },
          score: {
            title: "Le score et ses raisons",
            body: "Le score vient du moteur de matching de la prospection, jamais d'un calcul local. La ligne sous le nom détaille les critères satisfaits et les écarts qui restent.",
            consequence:
              "« Cibler » désigne l'acquéreur destinataire de la sélection, sans rien envoyer.",
          },
          lien: {
            title: "Le lien partageable",
            body: "Une fois un acquéreur ciblé, « Générer le lien partageable » crée une page publique où il note chaque bien du lot et te renvoie son avis.",
            consequence:
              "La visite explique ce bouton sans l'actionner : aucun lien public n'est créé pendant la visite.",
          },
        },
      },
      crm: {
        title: "Clients et portefeuille",
        description:
          "Enregistrer un client, suivre son avancement, ajouter un bien et lire l'état du portefeuille.",
        steps: {
          leadCreate: {
            title: "Créer un client",
            body: "L'action d'en-tête ouvre la fiche de création : nom, coordonnées, budget et mode de financement.",
            consequence: "Le client n'existe qu'après ta validation dans le formulaire.",
          },
          leadKinds: {
            title: "Acquéreur ou propriétaire",
            body: "Chaque client porte un type : l'acquéreur cherche un bien, le propriétaire en confie un. Les zones les séparent pour que tu saches quoi faire de chacun.",
          },
          leadPipeline: {
            title: "L'avancement",
            body: "L'entonnoir situe tes clients : nouveau, contacté, qualifié, visite, offre, gagné ou perdu. Le statut se change dans la vue liste.",
          },
          leadOpen: {
            title: "Ouvrir une fiche",
            body: "L'activité récente mène à la fiche du client. Elle réunit ses coordonnées et son historique : appels, visites, estimations, mandats.",
          },
          propertyCreate: {
            title: "Ajouter un bien",
            body: "Même principe côté portefeuille : l'action d'en-tête ouvre la saisie du bien — adresse, surface, prix, diagnostics.",
            consequence: "Le bien n'est enregistré qu'après ta validation dans le formulaire.",
          },
          propertyIndicators: {
            title: "L'état du portefeuille",
            body: "Les biens sont répartis par situation : en commercialisation, à compléter, entrés récemment, clos. Un bien à compléter est un bien qui se vend mal.",
          },
          propertyViews: {
            title: "Trois lectures du même stock",
            body: "Cockpit pour l'état métier, kanban pour glisser un bien d'une étape à l'autre, liste pour comparer prix et surfaces.",
          },
          propertyOpen: {
            title: "Ouvrir un bien",
            body: "La fiche du bien réunit photos, caractéristiques, mandat, visites et clients rattachés.",
          },
        },
      },
      estimations: {
        title: "Estimer un bien",
        description:
          "Lancer une estimation, suivre son avancement, la reprendre et exploiter son résultat.",
        steps: {
          create: {
            title: "Lancer une estimation",
            body: "L'entretien te pose les questions dans l'ordre : localisation, surface, état, atouts et défauts du bien.",
            consequence: "Tu peux interrompre l'entretien à tout moment : l'estimation reste en brouillon.",
          },
          pipeline: {
            title: "Où en sont tes estimations",
            body: "Une estimation passe par brouillon, entretien, récapitulatif, calcul, puis prête. Ce bloc compte celles présentes à chaque étape.",
          },
          resume: {
            title: "Reprendre une estimation",
            body: "La liste rassemble toutes tes estimations. Une ligne encore en cours propose de reprendre l'entretien là où il s'est arrêté.",
          },
          result: {
            title: "Ce que tu obtiens",
            body: "Une estimation prête donne une valeur de marché, une fourchette, les biens comparables retenus et le raisonnement associé.",
            consequence:
              "Depuis le résultat, tu crées le propriétaire et le mandat sans ressaisir le bien. L'envoi au client reste une action explicite de ta part.",
          },
        },
      },
      "communications-hitl": {
        title: "Envoyer un message et valider une action",
        description:
          "Où passent les messages avant de partir, et comment se tranche une action proposée par un agent.",
        steps: {
          transports: {
            title: "L'état réel de tes canaux",
            body: "Chaque canal affiche son état vrai : LIVE = envoi réel possible, CONFIG = variable manquante, donc aucun envoi.",
            consequence:
              "Aujourd'hui SMS et WhatsApp sont en CONFIG (Twilio non renseigné). L'email est configuré côté Resend mais aucun envoi réel n'a encore été effectué depuis ce dashboard.",
          },
          tabs: {
            title: "Le parcours d'un message",
            body: "Un message traverse quatre statuts : Brouillon, Validé, Envoyé, Échec. Les onglets filtrent la liste sur l'un d'eux.",
            consequence:
              "Un message n'arrive dans « Envoyé » que si le fournisseur a renvoyé une référence réelle. Sinon il reste en Échec avec la raison.",
          },
          edit: {
            title: "Corriger avant de valider",
            body: "Tant qu'un message est en brouillon ou validé, tu peux réécrire l'objet et le corps. C'est ton dernier mot sur le contenu.",
          },
          validate: {
            title: "La validation humaine",
            body: "« Valider » fait passer le brouillon en Validé. C'est toi qui décides qu'un message est prêt — jamais l'agent qui l'a rédigé.",
            consequence: "Valider ne fait rien partir : le message attend encore un envoi explicite.",
          },
          send: {
            title: "L'envoi, en dernier",
            body: "« Envoyer » n'apparaît que sur un message déjà validé, et reste inactif si le canal est en CONFIG.",
            consequence:
              "Un message n'est marqué « Envoyé » qu'avec une référence fournisseur réelle. Sans référence, il reste en Échec — jamais de faux envoi.",
          },
          proposal: {
            title: "Une action proposée par un agent",
            body: "Cette file liste les actions qu'un agent veut réaliser : le canal visé, l'agent demandeur et la date de la demande.",
            consequence: "Tant que tu n'as pas tranché, l'action reste en attente et ne s'exécute pas.",
          },
          justification: {
            title: "Sur quoi tu décides",
            body: "Chaque ligne porte sa justification : l'agent à l'origine, la cible concernée et l'empreinte du contenu proposé.",
            consequence: "L'empreinte garantit que le contenu approuvé est exactement celui qui sera utilisé.",
          },
          decision: {
            title: "Approuver ou refuser",
            body: "Deux boutons, deux issues : approuver autorise l'agent à réaliser l'action, refuser l'annule définitivement.",
            consequence:
              "Votre décision est enregistrée. Cette page n'exécute jamais silencieusement l'action.",
          },
        },
      },
      agents: {
        title: "Exploiter les agents",
        description:
          "Ce que ce cockpit fait des agents publiés : les lire, les lancer, suivre leur run et trancher leurs étapes de validation.",
        steps: {
          registry: {
            title: "Un registre, pas un atelier",
            body: "Cette page lit le registre Aigent et affiche exactement ce qu'il renvoie : ni agent inventé, ni run simulé.",
            consequence:
              "Les agents ne sont pas créés dans ce dashboard. Ils sont publiés par Aigent puis exploités ici.",
          },
          capabilities: {
            title: "Capacités et disponibilité",
            body: "Chaque agent publié annonce sa version, ses capacités et son statut. Seul un agent en production est exécutable.",
            consequence:
              "Le runtime Aigent n'est pas connecté sur cet environnement : les variables d'accès sont absentes et le registre ne renvoie donc aucun agent. L'écran l'affiche tel quel, sans en fabriquer un.",
          },
          run: {
            title: "Lancer et suivre un run",
            body: "Le bouton « Lancer » démarre un run sur le runtime, puis un suivi affiche son statut réel, ses événements et son résultat sourcé.",
            consequence:
              "Ce bouton n'apparaît qu'avec un agent en production dans le registre. Tant qu'Aigent n'est pas connecté, il n'y a rien à lancer.",
          },
          hitl: {
            title: "Les étapes de validation",
            body: "Quand un agent atteint une étape à effet réel, son run s'arrête et attend ta décision : approuver ou refuser.",
            consequence:
              "Le run reste bloqué tant que tu n'as pas tranché. Aucun agent ne franchit seul une étape sensible.",
          },
        },
      },
    },
    guard: {
      notice:
        "Visite guidée en cours : les envois, les décisions et les lancements sont désactivés. Termine ou passe la visite pour agir.",
      blockedTitle: "Action désactivée pendant la visite guidée",
    },
  },
  common: {
    yes: "Oui",
    no: "Non",
    empty: "—",
    error: "Erreur",
    networkError: "Erreur réseau.",
    busy: "…",
    loading: "Chargement…",
    saving: "Enregistrement…",
    httpError: (status: number) => `Erreur ${status}`,
    required: (label: string) => `${label} requis`,
  },
  logout: "Se déconnecter",
  brochure: {
    docTitle: "Avis de valeur",
    iframeTitle: "Avis de valeur immobilière",
    openPdf: "Ouvrir le PDF",
    mobileHint: "Le document ne s'affiche pas ? Ouvrez-le directement :",
  },
} as const;
