/**
 * lib/brochure/fixtures.ts — Fixtures partagées pour les tests de brochure/PDF.
 *
 * Fichier non-test (pas de `.test.ts`) : les tests peuvent l'importer sans
 * violer la règle biome `noExportsInTest`.
 */

import type { Estimation } from "@/lib/estimation/types";

/**
 * Estimation à l'état "ready", forme identique à la ligne persistée (celle
 * servie au moteur de rendu par pdf/route + brochure/pdf). La brochure lit
 * UNIQUEMENT ces champs — aucune donnée mockée hors de ce contrat.
 */
export const READY_FIXTURE: Estimation = {
  id: "275de142-cf6f-48d1-b9a4-bb84e3177792",
  userId: "u1",
  tenantId: "t1",
  status: "ready",
  property: {
    type_bien: "appartement",
    adresse: "12 rue de la Republique",
    ville: "Lyon",
    code_postal: "69002",
    secteur: "Presqu'ile",
    surface_habitable_m2: 75,
    surface_carrez_m2: 74,
    surface_carrez_confirmee: true,
    nombre_pieces: 3,
    nombre_chambres: 2,
    etage: 4,
    nb_etages_total: 6,
    ascenseur: true,
    vue: null,
    exposition: "sud",
    luminosite: null,
    hauteur_sous_plafond_m: null,
    stationnement: "aucun",
    nb_stationnements: null,
    cave: null,
    cave_surface_m2: null,
    terrasse_balcon_m2: null,
    jardin_m2: null,
    etat_general: "bon",
    annee_renovation: null,
    qualite_renovation: null,
    meuble: null,
    meuble_inclus: null,
    dpe_classe: "D",
    ges_classe: "D",
    annee_dpe: null,
    etat_copropriete: null,
    nombre_lots: null,
    charges_annuelles_eur: 2400,
    travaux_votes: null,
    standing_style: null,
    prestations: [],
    nuisances: null,
    motif_vente: null,
    delai_souhaite: null,
    occupation: "libre",
    loyer_mensuel_eur: null,
    commentaires: null,
  },
  fieldStatus: { surface_carrez_m2: "to_confirm", etage: "to_confirm" },
  market: {
    zone: "Lyon 2e",
    prix_median_m2: 5200,
    prix_moyen_m2: 5350,
    nb_transactions_12m: 84,
    tendance: "stable",
    delai_moyen_vente_jours: 62,
    dvf_comparables: Array.from({ length: 6 }, (_, i) => ({
      id: `dvf${i}`,
      date_mutation: `2025-0${(i % 9) + 1}-15`,
      adresse: "x",
      code_postal: "69002",
      ville: "Lyon",
      surface_reelle_bati: 70 + i,
      valeur_fonciere: 360000 + i * 10000,
      prix_m2: 5000 + i * 100,
      type_local: "Appartement",
      nombre_pieces: 3,
    })),
    listing_comparables: [
      {
        id: "l1",
        source: "apify",
        url: null,
        titre: "T3 lumineux",
        prix: 395000,
        surface_m2: 74,
        prix_m2: 5338,
        nb_pieces: 3,
        date_publication: null,
        statut: "actif",
        photo_url: "https://picsum.photos/seed/brochure-l1/400/280",
        lat: 45.7563,
        lon: 4.8397,
        quartier: "Presqu'île",
      },
      {
        id: "l2",
        source: "apify",
        url: null,
        titre: "Appartement 3 pièces rénové",
        prix: 402000,
        surface_m2: 76,
        prix_m2: 5289,
        nb_pieces: 3,
        date_publication: null,
        statut: "actif",
        photo_url: "https://picsum.photos/seed/brochure-l2/400/280",
        lat: 45.7541,
        lon: 4.8368,
        quartier: "Presqu'île",
      },
      {
        id: "l3",
        source: "apify",
        url: null,
        titre: "T3 avec balcon",
        prix: 388000,
        surface_m2: 73,
        prix_m2: 5315,
        nb_pieces: 3,
        date_publication: null,
        statut: "actif",
        photo_url: "https://picsum.photos/seed/brochure-l3/400/280",
        lat: 45.758,
        lon: 4.8352,
        quartier: "Presqu'île",
      },
    ],
    listing_source: {
      listings: [],
      source: "apify",
      rawCount: 3,
      filteredCount: 3,
      fallbackUsed: false,
    },
    subject_lat: 45.7558,
    subject_lon: 4.8378,
    fetched_at: "2026-07-13T00:00:00Z",
  },
  valuation: {
    basePerM2: 5200,
    adjustedPerM2: 5300,
    adjustments: [
      { label: "Exposition sud", type: "premium", pct: 2, rationale: "x" },
      { label: "DPE D", type: "discount", pct: 1, rationale: "x" },
    ],
    lowValue: 380000,
    marketValue: 397500,
    highValue: 415000,
    recommendedListingPrice: 409000,
    confidence: "moyenne",
    nbComparables: 6,
    engineVersion: "v1",
    confidenceFactors: {
      nbComparables: 6,
      cvPrixM2: 0.08,
      distanceMoyenneKm: 0.4,
      recenceMoyenneMois: 5,
    },
    dataStatus: "complete",
  },
  saleStrategies: [
    "Prix d'appel pour liquidite.",
    "Haut de fourchette pour valorisation.",
  ],
  branding: { name: "Azigo", monogram: "A" },
  createdAt: "2026-07-01T00:00:00Z",
  updatedAt: "2026-07-13T00:00:00Z",
};
